#libdload

obj-y := libdload.o

libdload-objs := cload.o getsection.o reloc.o

ccflags-y = -Wno-strict-prototypes -fomit-frame-pointer -DDISABLE_BRIDGE_DVFS

#Machine dependent
ccflags-y += -DTMS32060 -DOMAP_3430
ccflags-y += -DLINUX -D__KERNEL__

#Power management
ifeq ($(CONFIG_PM),)
ccflags-y += -DDISABLE_BRIDGE_PM
endif

#includes
ccflags-y += -I. -Iinclude -Idrivers/dsp/dspbridge/mpu_driver/inc -Idrivers/dsp/dspbridge/mpu_driver/inc/linux -include ./include/linux/autoconf.h -Iinclude/linux

# Debug
ifeq ($(CONFIG_DEBUG_KERNEL),y)
ccflags-y += -DGT_TRACE -DDEBUG
endif

ifeq ($(CONFIG_MPU_BRIDGE),m)
ccflags-y += -DMODULE
endif
