/*
 * dspbridge/src/hal/common/mbox/MLBAccInt.h
 *
 * DSP-BIOS Bridge driver support functions for TI OMAP processors.
 *
 * Copyright (C) 2007 Texas Instruments, Inc.
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * THIS PACKAGE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */


#ifndef _MLB_ACC_INT_H
#define _MLB_ACC_INT_H

#if defined(__cplusplus)
extern "C" {
#endif  /* defined(__cplusplus) */


/*****************************************************************************
* EXPORTED DEFINITIONS
******************************************************************************
*/

/* Mappings of level 1 EASI function numbers to function names */

#define EASIL1_MLBMAILBOX_REVISIONReadRegister32   MLB_BASE_EASIL1 + 0
#define EASIL1_MLBMAILBOX_REVISIONRevRead32        MLB_BASE_EASIL1 + 1
#define EASIL1_MLBMAILBOX_REVISIONRevGet32          MLB_BASE_EASIL1 + 2
#define EASIL1_MLBMAILBOX_SYSCONFIGReadRegister32   MLB_BASE_EASIL1 + 3
#define EASIL1_MLBMAILBOX_SYSCONFIGWriteRegister32  MLB_BASE_EASIL1 + 4
#define EASIL1_MLBMAILBOX_SYSCONFIGClockActivityRead32 MLB_BASE_EASIL1 + 5
#define EASIL1_MLBMAILBOX_SYSCONFIGClockActivityGet32  MLB_BASE_EASIL1 + 6
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeRead32   MLB_BASE_EASIL1 + 7
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeReadIsb0032 MLB_BASE_EASIL1 + 8
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeReadIsb0132 MLB_BASE_EASIL1 + 9
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeReadIsb1032 \
							MLB_BASE_EASIL1 + 10
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeReadIsb1132 \
							MLB_BASE_EASIL1 + 11
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeGet32  MLB_BASE_EASIL1 + 12
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeIsb0032  MLB_BASE_EASIL1 + 13
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeIsb0132  MLB_BASE_EASIL1 + 14
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeIsb1032  MLB_BASE_EASIL1 + 15
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeIsb1132  MLB_BASE_EASIL1 + 16
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeWrite32  MLB_BASE_EASIL1 + 17
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeWriteb0032 MLB_BASE_EASIL1 + 18
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeWriteb0132 MLB_BASE_EASIL1 + 19
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeWriteb1032 MLB_BASE_EASIL1 + 20
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeWriteb1132 MLB_BASE_EASIL1 + 21
#define EASIL1_MLBMAILBOX_SYSCONFIGSIdleModeSet32  MLB_BASE_EASIL1 + 22
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetRead32 MLB_BASE_EASIL1 + 23
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetReadIsb032 \
						MLB_BASE_EASIL1 + 24
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetReadIsb132 \
						MLB_BASE_EASIL1 + 25
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetGet32  MLB_BASE_EASIL1 + 26
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetIsb032 MLB_BASE_EASIL1 + 27
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetIsb132  MLB_BASE_EASIL1 + 28
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetWrite32 MLB_BASE_EASIL1 + 29
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetWriteb032 \
						MLB_BASE_EASIL1 + 30
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetWriteb132 \
						MLB_BASE_EASIL1 + 31
#define EASIL1_MLBMAILBOX_SYSCONFIGSoftResetSet32 \
						MLB_BASE_EASIL1 + 32
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleRead32 \
						MLB_BASE_EASIL1 + 33
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleReadIsb032 \
						MLB_BASE_EASIL1 + 34
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleReadIsb132  \
						MLB_BASE_EASIL1 + 35
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleGet32   MLB_BASE_EASIL1 + 36
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleIsb032  MLB_BASE_EASIL1 + 37
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleIsb132  MLB_BASE_EASIL1 + 38
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleWrite32   MLB_BASE_EASIL1 + 39
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleWriteb032  MLB_BASE_EASIL1 + 40
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleWriteb132  MLB_BASE_EASIL1 + 41
#define EASIL1_MLBMAILBOX_SYSCONFIGAutoIdleSet32   MLB_BASE_EASIL1 + 42
#define EASIL1_MLBMAILBOX_SYSSTATUSReadRegister32  MLB_BASE_EASIL1 + 43
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneRead32  MLB_BASE_EASIL1 + 44
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneReadIsrstongoing32 \
						MLB_BASE_EASIL1 + 45
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneReadIsrstcomp32  \
						MLB_BASE_EASIL1 + 46
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneGet32 MLB_BASE_EASIL1 + 47
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneIsrstongoing32  \
						MLB_BASE_EASIL1 + 48
#define EASIL1_MLBMAILBOX_SYSSTATUSResetDoneIsrstcomp32 \
						MLB_BASE_EASIL1 + 49
#define EASIL1_MLBMAILBOX_MESSAGE___0_15ReadRegister32 \
						MLB_BASE_EASIL1 + 50
#define EASIL1_MLBMAILBOX_MESSAGE___0_15WriteRegister32  \
						MLB_BASE_EASIL1 + 51
#define EASIL1_MLBMAILBOX_MESSAGE___0_15MessageValueMBmRead32 \
						MLB_BASE_EASIL1 + 52
#define EASIL1_MLBMAILBOX_MESSAGE___0_15MessageValueMBmGet32  \
						MLB_BASE_EASIL1 + 53
#define EASIL1_MLBMAILBOX_MESSAGE___0_15MessageValueMBmWrite32 \
						MLB_BASE_EASIL1 + 54
#define EASIL1_MLBMAILBOX_MESSAGE___0_15MessageValueMBmSet32  \
						MLB_BASE_EASIL1 + 55
#define EASIL1_MLBMAILBOX_FIFOSTATUS___0_15ReadRegister32  \
						MLB_BASE_EASIL1 + 56
#define EASIL1_MLBMAILBOX_FIFOSTATUS___0_15FifoFullMBmRead32 \
						MLB_BASE_EASIL1 + 57
#define EASIL1_MLBMAILBOX_FIFOSTATUS___0_15FifoFullMBmGet32  \
						MLB_BASE_EASIL1 + 58
#define EASIL1_MLBMAILBOX_MSGSTATUS___0_15ReadRegister32  \
						MLB_BASE_EASIL1 + 59
#define EASIL1_MLBMAILBOX_MSGSTATUS___0_15NbOfMsgMBmRead32  \
						MLB_BASE_EASIL1 + 60
#define EASIL1_MLBMAILBOX_MSGSTATUS___0_15NbOfMsgMBmGet32 \
						MLB_BASE_EASIL1 + 61
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3ReadRegister32  \
						MLB_BASE_EASIL1 + 62
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3WriteRegister32 \
						MLB_BASE_EASIL1 + 63
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB15Read32 \
						MLB_BASE_EASIL1 + 64
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB15Get32 \
						MLB_BASE_EASIL1 + 65
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB15Write32 \
						MLB_BASE_EASIL1 + 66
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB15Set32 \
						MLB_BASE_EASIL1 + 67
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB15Read32 \
						MLB_BASE_EASIL1 + 68
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB15Get32 \
						MLB_BASE_EASIL1 + 69
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB15Write32 \
						MLB_BASE_EASIL1 + 70
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB15Set32 \
						MLB_BASE_EASIL1 + 71
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB14Read32 \
						MLB_BASE_EASIL1 + 72
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB14Get32 \
						MLB_BASE_EASIL1 + 73
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB14Write32 \
						MLB_BASE_EASIL1 + 74
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB14Set32 \
						MLB_BASE_EASIL1 + 75
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB14Read32  \
						MLB_BASE_EASIL1 + 76
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB14Get32 \
						MLB_BASE_EASIL1 + 77
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB14Write32 \
						MLB_BASE_EASIL1 + 78
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB14Set32 \
						MLB_BASE_EASIL1 + 79
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB13Read32 \
						MLB_BASE_EASIL1 + 80
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB13Get32  \
						MLB_BASE_EASIL1 + 81
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB13Write32 \
						MLB_BASE_EASIL1 + 82
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB13Set32 \
						MLB_BASE_EASIL1 + 83
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB13Read32 \
						MLB_BASE_EASIL1 + 84
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB13Get32  \
						MLB_BASE_EASIL1 + 85
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB13Write32 \
						MLB_BASE_EASIL1 + 86
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB13Set32  \
						MLB_BASE_EASIL1 + 87
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB12Read32 \
						MLB_BASE_EASIL1 + 88
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB12Get32 \
						MLB_BASE_EASIL1 + 89
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB12Write32\
						MLB_BASE_EASIL1 + 90
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB12Set32 \
						MLB_BASE_EASIL1 + 91
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB12Read32\
						MLB_BASE_EASIL1 + 92
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB12Get32 \
						MLB_BASE_EASIL1 + 93
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB12Write32 \
						MLB_BASE_EASIL1 + 94
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB12Set32 \
						MLB_BASE_EASIL1 + 95
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB11Read32 \
						MLB_BASE_EASIL1 + 96
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB11Get32  \
						MLB_BASE_EASIL1 + 97
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB11Write32 \
						MLB_BASE_EASIL1 + 98
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB11Set32  \
						MLB_BASE_EASIL1 + 99
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB11Read32  \
						MLB_BASE_EASIL1 + 100
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB11Get32  \
						MLB_BASE_EASIL1 + 101
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB11Write32 \
						MLB_BASE_EASIL1 + 102
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB11Set32 \
						MLB_BASE_EASIL1 + 103
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB10Read32 \
						MLB_BASE_EASIL1 + 104
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB10Get32  \
						MLB_BASE_EASIL1 + 105
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB10Write32 \
						MLB_BASE_EASIL1 + 106
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB10Set32  \
						MLB_BASE_EASIL1 + 107
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB10Read32  \
						MLB_BASE_EASIL1 + 108
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB10Get32 \
						MLB_BASE_EASIL1 + 109
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB10Write32 \
						MLB_BASE_EASIL1 + 110
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB10Set32  \
						MLB_BASE_EASIL1 + 111
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB9Read32  \
						MLB_BASE_EASIL1 + 112
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB9Get32  \
						MLB_BASE_EASIL1 + 113
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB9Write32 \
						MLB_BASE_EASIL1 + 114
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB9Set32  \
						MLB_BASE_EASIL1 + 115
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB9Read32 \
						MLB_BASE_EASIL1 + 116
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB9Get32 \
						MLB_BASE_EASIL1 + 117
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB9Write32 \
						MLB_BASE_EASIL1 + 118
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB9Set32 \
						MLB_BASE_EASIL1 + 119
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB8Read32 \
						MLB_BASE_EASIL1 + 120
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB8Get32  \
						MLB_BASE_EASIL1 + 121
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB8Write32 \
						MLB_BASE_EASIL1 + 122
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB8Set32  \
						MLB_BASE_EASIL1 + 123
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB8Read32  \
						MLB_BASE_EASIL1 + 124
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB8Get32 \
						MLB_BASE_EASIL1 + 125
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB8Write32 \
						MLB_BASE_EASIL1 + 126
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB8Set32  \
						MLB_BASE_EASIL1 + 127
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB7Read32 \
						MLB_BASE_EASIL1 + 128
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB7Get32 \
						MLB_BASE_EASIL1 + 129
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB7Write32 \
						MLB_BASE_EASIL1 + 130
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB7Set32 \
						MLB_BASE_EASIL1 + 131
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB7Read32  \
						MLB_BASE_EASIL1 + 132
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB7Get32  \
						MLB_BASE_EASIL1 + 133
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB7Write32  \
						MLB_BASE_EASIL1 + 134
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB7Set32  \
						MLB_BASE_EASIL1 + 135
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB6Read32 \
						MLB_BASE_EASIL1 + 136
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB6Get32   \
						MLB_BASE_EASIL1 + 137
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB6Write32 \
						MLB_BASE_EASIL1 + 138
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB6Set32 \
						MLB_BASE_EASIL1 + 139
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB6Read32 \
						MLB_BASE_EASIL1 + 140
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB6Get32  \
						MLB_BASE_EASIL1 + 141
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB6Write32  \
						MLB_BASE_EASIL1 + 142
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB6Set32   \
						MLB_BASE_EASIL1 + 143
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB5Read32  \
						MLB_BASE_EASIL1 + 144
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB5Get32  \
						MLB_BASE_EASIL1 + 145
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB5Write32  \
						MLB_BASE_EASIL1 + 146
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB5Set32  \
						MLB_BASE_EASIL1 + 147
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB5Read32 \
						MLB_BASE_EASIL1 + 148
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB5Get32  \
						MLB_BASE_EASIL1 + 149
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB5Write32  \
						MLB_BASE_EASIL1 + 150
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB5Set32  \
						MLB_BASE_EASIL1 + 151
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB4Read32 \
						MLB_BASE_EASIL1 + 152
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB4Get32   \
						MLB_BASE_EASIL1 + 153
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB4Write32 \
						MLB_BASE_EASIL1 + 154
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB4Set32  \
						MLB_BASE_EASIL1 + 155
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB4Read32 \
						MLB_BASE_EASIL1 + 156
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB4Get32  \
						MLB_BASE_EASIL1 + 157
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB4Write32 \
						MLB_BASE_EASIL1 + 158
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB4Set32  \
						MLB_BASE_EASIL1 + 159
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB3Read32 \
						MLB_BASE_EASIL1 + 160
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB3Get32  \
						MLB_BASE_EASIL1 + 161
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB3Write32 \
						MLB_BASE_EASIL1 + 162
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB3Set32  \
						MLB_BASE_EASIL1 + 163
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB3Read32 \
						MLB_BASE_EASIL1 + 164
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB3Get32  \
						MLB_BASE_EASIL1 + 165
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB3Write32  \
						MLB_BASE_EASIL1 + 166
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB3Set32  \
						MLB_BASE_EASIL1 + 167
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB2Read32 \
						MLB_BASE_EASIL1 + 168
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB2Get32 \
						MLB_BASE_EASIL1 + 169
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB2Write32 \
						MLB_BASE_EASIL1 + 170
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB2Set32  \
						MLB_BASE_EASIL1 + 171
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB2Read32  \
						MLB_BASE_EASIL1 + 172
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB2Get32  \
						MLB_BASE_EASIL1 + 173
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB2Write32 \
						MLB_BASE_EASIL1 + 174
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB2Set32  \
						MLB_BASE_EASIL1 + 175
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB1Read32  \
						MLB_BASE_EASIL1 + 176
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB1Get32   \
						MLB_BASE_EASIL1 + 177
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB1Write32 \
						MLB_BASE_EASIL1 + 178
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB1Set32 \
						MLB_BASE_EASIL1 + 179
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB1Read32 \
						MLB_BASE_EASIL1 + 180
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB1Get32 \
						MLB_BASE_EASIL1 + 181
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB1Write32  \
						MLB_BASE_EASIL1 + 182
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB1Set32  \
						MLB_BASE_EASIL1 + 183
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB0Read32 \
						MLB_BASE_EASIL1 + 184
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB0Get32  \
						MLB_BASE_EASIL1 + 185
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB0Write32 \
						MLB_BASE_EASIL1 + 186
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NotFullStatusUuMB0Set32  \
						MLB_BASE_EASIL1 + 187
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB0Read32 \
						MLB_BASE_EASIL1 + 188
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB0Get32  \
						MLB_BASE_EASIL1 + 189
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB0Write32 \
						MLB_BASE_EASIL1 + 190
#define EASIL1_MLBMAILBOX_IRQSTATUS___0_3NewMsgStatusUuMB0Set32   \
						MLB_BASE_EASIL1 + 191
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3ReadRegister32    \
						MLB_BASE_EASIL1 + 192
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3WriteRegister32   \
						MLB_BASE_EASIL1 + 193
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB15Read32 \
						MLB_BASE_EASIL1 + 194
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB15Get32 \
						MLB_BASE_EASIL1 + 195
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB15Write32 \
						MLB_BASE_EASIL1 + 196
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB15Set32 \
						MLB_BASE_EASIL1 + 197
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB15Read32 \
						MLB_BASE_EASIL1 + 198
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB15Get32  \
						MLB_BASE_EASIL1 + 199
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB15Write32 \
						MLB_BASE_EASIL1 + 200
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB15Set32  \
						MLB_BASE_EASIL1 + 201
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB14Read32 \
						MLB_BASE_EASIL1 + 202
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB14Get32  \
						MLB_BASE_EASIL1 + 203
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB14Write32  \
						MLB_BASE_EASIL1 + 204
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB14Set32  \
						MLB_BASE_EASIL1 + 205
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB14Read32  \
						MLB_BASE_EASIL1 + 206
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB14Get32 \
						MLB_BASE_EASIL1 + 207
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB14Write32 \
						MLB_BASE_EASIL1 + 208
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB14Set32   \
						MLB_BASE_EASIL1 + 209
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB13Read32 \
						MLB_BASE_EASIL1 + 210
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB13Get32  \
						MLB_BASE_EASIL1 + 211
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB13Write32 \
						MLB_BASE_EASIL1 + 212
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB13Set32 \
						MLB_BASE_EASIL1 + 213
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB13Read32 \
						MLB_BASE_EASIL1 + 214
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB13Get32 \
						MLB_BASE_EASIL1 + 215
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB13Write32 \
						MLB_BASE_EASIL1 + 216
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB13Set32   \
						MLB_BASE_EASIL1 + 217
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB12Read32 \
						MLB_BASE_EASIL1 + 218
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB12Get32 \
						MLB_BASE_EASIL1 + 219
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB12Write32  \
						MLB_BASE_EASIL1 + 220
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB12Set32 \
						MLB_BASE_EASIL1 + 221
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB12Read32 \
						MLB_BASE_EASIL1 + 222
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB12Get32  \
						MLB_BASE_EASIL1 + 223
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB12Write32 \
						MLB_BASE_EASIL1 + 224
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB12Set32  \
						MLB_BASE_EASIL1 + 225
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB11Read32 \
						MLB_BASE_EASIL1 + 226
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB11Get32  \
						MLB_BASE_EASIL1 + 227
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB11Write32 \
						MLB_BASE_EASIL1 + 228
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB11Set32  \
						MLB_BASE_EASIL1 + 229
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB11Read32  \
						MLB_BASE_EASIL1 + 230
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB11Get32 \
						MLB_BASE_EASIL1 + 231
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB11Write32 \
						MLB_BASE_EASIL1 + 232
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB11Set32 \
						MLB_BASE_EASIL1 + 233
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB10Read32 \
						MLB_BASE_EASIL1 + 234
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB10Get32  \
						MLB_BASE_EASIL1 + 235
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB10Write32 \
						MLB_BASE_EASIL1 + 236
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB10Set32  \
						MLB_BASE_EASIL1 + 237
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB10Read32  \
						MLB_BASE_EASIL1 + 238
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB10Get32 \
						MLB_BASE_EASIL1 + 239
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB10Write32 \
						MLB_BASE_EASIL1 + 240
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB10Set32   \
						MLB_BASE_EASIL1 + 241
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB9Read32  \
						MLB_BASE_EASIL1 + 242
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB9Get32 \
						MLB_BASE_EASIL1 + 243
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB9Write32 \
						MLB_BASE_EASIL1 + 244
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB9Set32  \
						MLB_BASE_EASIL1 + 245
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB9Read32  \
						MLB_BASE_EASIL1 + 246
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB9Get32  \
						MLB_BASE_EASIL1 + 247
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB9Write32  \
						MLB_BASE_EASIL1 + 248
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB9Set32  \
						MLB_BASE_EASIL1 + 249
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB8Read32  \
						MLB_BASE_EASIL1 + 250
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB8Get32   \
						MLB_BASE_EASIL1 + 251
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB8Write32 \
						MLB_BASE_EASIL1 + 252
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB8Set32   \
						MLB_BASE_EASIL1 + 253
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB8Read32 \
						MLB_BASE_EASIL1 + 254
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB8Get32 \
						MLB_BASE_EASIL1 + 255
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB8Write32 \
						MLB_BASE_EASIL1 + 256
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB8Set32  \
						MLB_BASE_EASIL1 + 257
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB7Read32  \
						MLB_BASE_EASIL1 + 258
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB7Get32   \
						MLB_BASE_EASIL1 + 259
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB7Write32 \
						MLB_BASE_EASIL1 + 260
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB7Set32  \
						MLB_BASE_EASIL1 + 261
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB7Read32  \
						MLB_BASE_EASIL1 + 262
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB7Get32  \
						MLB_BASE_EASIL1 + 263
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB7Write32 \
						MLB_BASE_EASIL1 + 264
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB7Set32    \
						MLB_BASE_EASIL1 + 265
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB6Read32  \
						MLB_BASE_EASIL1 + 266
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB6Get32 \
						MLB_BASE_EASIL1 + 267
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB6Write32 \
						MLB_BASE_EASIL1 + 268
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB6Set32  \
						MLB_BASE_EASIL1 + 269
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB6Read32 \
						MLB_BASE_EASIL1 + 270
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB6Get32  \
						MLB_BASE_EASIL1 + 271
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB6Write32  \
						MLB_BASE_EASIL1 + 272
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB6Set32 \
						MLB_BASE_EASIL1 + 273
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB5Read32 \
						MLB_BASE_EASIL1 + 274
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB5Get32 \
						MLB_BASE_EASIL1 + 275
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB5Write32 \
						MLB_BASE_EASIL1 + 276
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB5Set32  \
						MLB_BASE_EASIL1 + 277
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB5Read32  \
						MLB_BASE_EASIL1 + 278
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB5Get32  \
						MLB_BASE_EASIL1 + 279
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB5Write32 \
						MLB_BASE_EASIL1 + 280
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB5Set32  \
						MLB_BASE_EASIL1 + 281
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB4Read32  \
						MLB_BASE_EASIL1 + 282
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB4Get32  \
						MLB_BASE_EASIL1 + 283
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB4Write32 \
						MLB_BASE_EASIL1 + 284
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB4Set32   \
						MLB_BASE_EASIL1 + 285
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB4Read32  \
						MLB_BASE_EASIL1 + 286
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB4Get32   \
						MLB_BASE_EASIL1 + 287
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB4Write32 \
						MLB_BASE_EASIL1 + 288
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB4Set32 \
						MLB_BASE_EASIL1 + 289
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB3Read32  \
						MLB_BASE_EASIL1 + 290
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB3Get32  \
						MLB_BASE_EASIL1 + 291
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB3Write32 \
						MLB_BASE_EASIL1 + 292
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB3Set32 \
						MLB_BASE_EASIL1 + 293
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB3Read32  \
						MLB_BASE_EASIL1 + 294
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB3Get32  \
						MLB_BASE_EASIL1 + 295
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB3Write32 \
						MLB_BASE_EASIL1 + 296
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB3Set32    \
						MLB_BASE_EASIL1 + 297
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB2Read32 \
						MLB_BASE_EASIL1 + 298
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB2Get32 \
						MLB_BASE_EASIL1 + 299
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB2Write32 \
						MLB_BASE_EASIL1 + 300
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB2Set32 \
						MLB_BASE_EASIL1 + 301
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB2Read32  \
						MLB_BASE_EASIL1 + 302
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB2Get32   \
						MLB_BASE_EASIL1 + 303
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB2Write32  \
						MLB_BASE_EASIL1 + 304
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB2Set32   \
						MLB_BASE_EASIL1 + 305
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB1Read32 \
						MLB_BASE_EASIL1 + 306
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB1Get32 \
						MLB_BASE_EASIL1 + 307
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB1Write32 \
						MLB_BASE_EASIL1 + 308
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB1Set32  \
						MLB_BASE_EASIL1 + 309
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB1Read32  \
						MLB_BASE_EASIL1 + 310
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB1Get32   \
						MLB_BASE_EASIL1 + 311
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB1Write32 \
						MLB_BASE_EASIL1 + 312
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB1Set32  \
						MLB_BASE_EASIL1 + 313
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB0Read32  \
						MLB_BASE_EASIL1 + 314
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB0Get32  \
						MLB_BASE_EASIL1 + 315
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB0Write32 \
						MLB_BASE_EASIL1 + 316
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NotFullEnableUuMB0Set32   \
						MLB_BASE_EASIL1 + 317
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB0Read32  \
						MLB_BASE_EASIL1 + 318
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB0Get32  \
						MLB_BASE_EASIL1 + 319
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB0Write32  \
						MLB_BASE_EASIL1 + 320
#define EASIL1_MLBMAILBOX_IRQENABLE___0_3NewMsgEnableUuMB0Set32  \
						MLB_BASE_EASIL1 + 321


/* Register set MAILBOX_MESSAGE___REGSET_0_15 address offset, bank address
 * increment and number of banks */

#define MLB_MAILBOX_MESSAGE___REGSET_0_15_OFFSET    (UWORD32)(0x0040)
#define MLB_MAILBOX_MESSAGE___REGSET_0_15_STEP   (UWORD32)(0x0004)
#define MLB_MAILBOX_MESSAGE___REGSET_0_15_BANKS  (UWORD32)(16)

/* Register offset address definitions relative to register set
 * MAILBOX_MESSAGE___REGSET_0_15 */

#define MLB_MAILBOX_MESSAGE___0_15_OFFSET   (UWORD32)(0x0)


/* Register set MAILBOX_FIFOSTATUS___REGSET_0_15 address offset, bank address
 * increment and number of banks */

#define MLB_MAILBOX_FIFOSTATUS___REGSET_0_15_OFFSET  (UWORD32)(0x0080)
#define MLB_MAILBOX_FIFOSTATUS___REGSET_0_15_STEP   (UWORD32)(0x0004)
#define MLB_MAILBOX_FIFOSTATUS___REGSET_0_15_BANKS   (UWORD32)(16)

/* Register offset address definitions relative to register set
 * MAILBOX_FIFOSTATUS___REGSET_0_15 */

#define MLB_MAILBOX_FIFOSTATUS___0_15_OFFSET    (UWORD32)(0x0)


/* Register set MAILBOX_MSGSTATUS___REGSET_0_15 address offset, bank address
 * increment and number of banks */

#define MLB_MAILBOX_MSGSTATUS___REGSET_0_15_OFFSET  (UWORD32)(0x00c0)
#define MLB_MAILBOX_MSGSTATUS___REGSET_0_15_STEP    (UWORD32)(0x0004)
#define MLB_MAILBOX_MSGSTATUS___REGSET_0_15_BANKS   (UWORD32)(16)

/* Register offset address definitions relative to register set
 * MAILBOX_MSGSTATUS___REGSET_0_15 */

#define MLB_MAILBOX_MSGSTATUS___0_15_OFFSET    (UWORD32)(0x0)


/* Register set MAILBOX_IRQSTATUS___REGSET_0_3 address offset, bank address
 * increment and number of banks */

#define MLB_MAILBOX_IRQSTATUS___REGSET_0_3_OFFSET        (UWORD32)(0x0100)
#define MLB_MAILBOX_IRQSTATUS___REGSET_0_3_STEP          (UWORD32)(0x0008)
#define MLB_MAILBOX_IRQSTATUS___REGSET_0_3_BANKS        (UWORD32)(4)

/* Register offset address definitions relative to register set
 * MAILBOX_IRQSTATUS___REGSET_0_3 */

#define MLB_MAILBOX_IRQSTATUS___0_3_OFFSET        (UWORD32)(0x0)


/* Register set MAILBOX_IRQENABLE___REGSET_0_3 address offset, bank address
 * increment and number of banks */

#define MLB_MAILBOX_IRQENABLE___REGSET_0_3_OFFSET     (UWORD32)(0x0104)
#define MLB_MAILBOX_IRQENABLE___REGSET_0_3_STEP     (UWORD32)(0x0008)
#define MLB_MAILBOX_IRQENABLE___REGSET_0_3_BANKS    (UWORD32)(4)

/* Register offset address definitions relative to register set
 * MAILBOX_IRQENABLE___REGSET_0_3 */

#define MLB_MAILBOX_IRQENABLE___0_3_OFFSET          (UWORD32)(0x0)


/* Register offset address definitions */

#define MLB_MAILBOX_REVISION_OFFSET             (UWORD32)(0x0)
#define MLB_MAILBOX_SYSCONFIG_OFFSET            (UWORD32)(0x10)
#define MLB_MAILBOX_SYSSTATUS_OFFSET            (UWORD32)(0x14)


/* Bitfield mask and offset declarations */

#define MLB_MAILBOX_REVISION_Rev_MASK         (UWORD32)(0xff)
#define MLB_MAILBOX_REVISION_Rev_OFFSET       (UWORD32)(0)
#define MLB_MAILBOX_SYSCONFIG_ClockActivity_MASK    (UWORD32)(0x100)
#define MLB_MAILBOX_SYSCONFIG_ClockActivity_OFFSET   (UWORD32)(8)
#define MLB_MAILBOX_SYSCONFIG_SIdleMode_MASK        (UWORD32)(0x18)
#define MLB_MAILBOX_SYSCONFIG_SIdleMode_OFFSET      (UWORD32)(3)
#define MLB_MAILBOX_SYSCONFIG_SoftReset_MASK        (UWORD32)(0x2)
#define MLB_MAILBOX_SYSCONFIG_SoftReset_OFFSET      (UWORD32)(1)
#define MLB_MAILBOX_SYSCONFIG_AutoIdle_MASK          (UWORD32)(0x1)
#define MLB_MAILBOX_SYSCONFIG_AutoIdle_OFFSET        (UWORD32)(0)
#define MLB_MAILBOX_SYSSTATUS_ResetDone_MASK         (UWORD32)(0x1)
#define MLB_MAILBOX_SYSSTATUS_ResetDone_OFFSET         (UWORD32)(0)
#define MLB_MAILBOX_MESSAGE___0_15_MessageValueMBm_MASK \
							(UWORD32)(0xffffffff)
#define MLB_MAILBOX_MESSAGE___0_15_MessageValueMBm_OFFSET \
							(UWORD32)(0)
#define MLB_MAILBOX_FIFOSTATUS___0_15_FifoFullMBm_MASK   (UWORD32)(0x1)
#define MLB_MAILBOX_FIFOSTATUS___0_15_FifoFullMBm_OFFSET  (UWORD32)(0)
#define MLB_MAILBOX_MSGSTATUS___0_15_NbOfMsgMBm_MASK    (UWORD32)(0x7f)
#define MLB_MAILBOX_MSGSTATUS___0_15_NbOfMsgMBm_OFFSET    (UWORD32)(0)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB15_MASK  \
							(UWORD32)(0x80000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB15_OFFSET  \
							(UWORD32)(31)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB15_MASK  \
							(UWORD32)(0x40000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB15_OFFSET  \
							(UWORD32)(30)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB14_MASK    \
							(UWORD32)(0x20000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB14_OFFSET  \
							(UWORD32)(29)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB14_MASK   \
							(UWORD32)(0x10000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB14_OFFSET  \
							(UWORD32)(28)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB13_MASK    \
							(UWORD32)(0x8000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB13_OFFSET  \
							(UWORD32)(27)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB13_MASK    \
							(UWORD32)(0x4000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB13_OFFSET    \
							(UWORD32)(26)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB12_MASK     \
							(UWORD32)(0x2000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB12_OFFSET    \
							(UWORD32)(25)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB12_MASK    \
							(UWORD32)(0x1000000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB12_OFFSET    \
							(UWORD32)(24)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB11_MASK    \
							(UWORD32)(0x800000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB11_OFFSET    \
							(UWORD32)(23)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB11_MASK \
							(UWORD32)(0x400000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB11_OFFSET  \
							(UWORD32)(22)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB10_MASK  \
							(UWORD32)(0x200000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB10_OFFSET    \
							(UWORD32)(21)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB10_MASK   \
							(UWORD32)(0x100000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB10_OFFSET \
							(UWORD32)(20)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB9_MASK   \
							(UWORD32)(0x80000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB9_OFFSET (UWORD32)(19)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB9_MASK  \
							(UWORD32)(0x40000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB9_OFFSET \
							(UWORD32)(18)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB8_MASK  \
							(UWORD32)(0x20000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB8_OFFSET  \
							(UWORD32)(17)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB8_MASK  \
							(UWORD32)(0x10000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB8_OFFSET \
							(UWORD32)(16)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB7_MASK   \
							(UWORD32)(0x8000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB7_OFFSET \
							(UWORD32)(15)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB7_MASK  \
							(UWORD32)(0x4000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB7_OFFSET  \
							(UWORD32)(14)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB6_MASK  \
							(UWORD32)(0x2000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB6_OFFSET  \
							(UWORD32)(13)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB6_MASK  \
							(UWORD32)(0x1000)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB6_OFFSET \
							(UWORD32)(12)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB5_MASK   \
							(UWORD32)(0x800)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB5_OFFSET  \
							(UWORD32)(11)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB5_MASK      \
							(UWORD32)(0x400)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB5_OFFSET  \
							(UWORD32)(10)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB4_MASK   \
							(UWORD32)(0x200)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB4_OFFSET  \
							(UWORD32)(9)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB4_MASK    \
							(UWORD32)(0x100)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB4_OFFSET  \
							(UWORD32)(8)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB3_MASK   \
							(UWORD32)(0x80)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB3_OFFSET  \
							(UWORD32)(7)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB3_MASK    \
							(UWORD32)(0x40)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB3_OFFSET  \
							(UWORD32)(6)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB2_MASK    \
							(UWORD32)(0x20)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB2_OFFSET  \
							(UWORD32)(5)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB2_MASK   \
							(UWORD32)(0x10)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB2_OFFSET  \
							(UWORD32)(4)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB1_MASK    \
							(UWORD32)(0x8)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB1_OFFSET  \
							(UWORD32)(3)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB1_MASK   \
							(UWORD32)(0x4)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB1_OFFSET  \
							(UWORD32)(2)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB0_MASK  \
							(UWORD32)(0x2)
#define MLB_MAILBOX_IRQSTATUS___0_3_NotFullStatusUuMB0_OFFSET  \
							(UWORD32)(1)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB0_MASK  \
							(UWORD32)(0x1)
#define MLB_MAILBOX_IRQSTATUS___0_3_NewMsgStatusUuMB0_OFFSET \
							(UWORD32)(0)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB15_MASK \
							(UWORD32)(0x80000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB15_OFFSET  \
							(UWORD32)(31)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB15_MASK   \
							(UWORD32)(0x40000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB15_OFFSET   \
							(UWORD32)(30)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB14_MASK   \
							(UWORD32)(0x20000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB14_OFFSET  \
							(UWORD32)(29)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB14_MASK  \
							(UWORD32)(0x10000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB14_OFFSET  \
							(UWORD32)(28)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB13_MASK  \
							(UWORD32)(0x8000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB13_OFFSET   \
							(UWORD32)(27)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB13_MASK  \
							(UWORD32)(0x4000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB13_OFFSET  \
							(UWORD32)(26)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB12_MASK   \
							(UWORD32)(0x2000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB12_OFFSET   \
							(UWORD32)(25)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB12_MASK   \
							(UWORD32)(0x1000000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB12_OFFSET  \
							(UWORD32)(24)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB11_MASK  \
							(UWORD32)(0x800000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB11_OFFSET   \
							(UWORD32)(23)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB11_MASK    \
							(UWORD32)(0x400000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB11_OFFSET  \
							(UWORD32)(22)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB10_MASK  \
							(UWORD32)(0x200000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB10_OFFSET  \
							(UWORD32)(21)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB10_MASK   \
							(UWORD32)(0x100000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB10_OFFSET   \
							(UWORD32)(20)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB9_MASK  \
							(UWORD32)(0x80000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB9_OFFSET  \
							(UWORD32)(19)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB9_MASK  \
							(UWORD32)(0x40000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB9_OFFSET  \
							(UWORD32)(18)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB8_MASK   \
							(UWORD32)(0x20000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB8_OFFSET \
							(UWORD32)(17)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB8_MASK  \
							(UWORD32)(0x10000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB8_OFFSET  \
							(UWORD32)(16)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB7_MASK  \
							(UWORD32)(0x8000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB7_OFFSET \
							(UWORD32)(15)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB7_MASK   \
							(UWORD32)(0x4000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB7_OFFSET   \
							(UWORD32)(14)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB6_MASK    \
							(UWORD32)(0x2000)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB6_OFFSET    \
							(UWORD32)(13)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB6_MASK  \
							(UWORD32)(0x1000)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB6_OFFSET   \
							(UWORD32)(12)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB5_MASK  \
							(UWORD32)(0x800)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB5_OFFSET  \
							(UWORD32)(11)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB5_MASK   \
							(UWORD32)(0x400)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB5_OFFSET  \
							(UWORD32)(10)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB4_MASK  \
							(UWORD32)(0x200)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB4_OFFSET  \
							(UWORD32)(9)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB4_MASK    \
							(UWORD32)(0x100)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB4_OFFSET  \
							(UWORD32)(8)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB3_MASK   \
							(UWORD32)(0x80)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB3_OFFSET \
							(UWORD32)(7)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB3_MASK \
							(UWORD32)(0x40)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB3_OFFSET (UWORD32)(6)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB2_MASK (UWORD32)(0x20)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB2_OFFSET (UWORD32)(5)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB2_MASK (UWORD32)(0x10)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB2_OFFSET (UWORD32)(4)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB1_MASK (UWORD32)(0x8)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB1_OFFSET (UWORD32)(3)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB1_MASK (UWORD32)(0x4)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB1_OFFSET (UWORD32)(2)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB0_MASK (UWORD32)(0x2)
#define MLB_MAILBOX_IRQENABLE___0_3_NotFullEnableUuMB0_OFFSET (UWORD32)(1)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB0_MASK (UWORD32)(0x1)
#define MLB_MAILBOX_IRQENABLE___0_3_NewMsgEnableUuMB0_OFFSET (UWORD32)(0)


/*****************************************************************************
* EXPORTED TYPES
******************************************************************************
*/

/* The following type definitions represent the enumerated values for
 * each bitfield */

typedef enum {
    MLBMAILBOX_SYSCONFIGSIdleModeb00 = 0x0000,
    MLBMAILBOX_SYSCONFIGSIdleModeb01 = 0x0001,
    MLBMAILBOX_SYSCONFIGSIdleModeb10 = 0x0002,
    MLBMAILBOX_SYSCONFIGSIdleModeb11 = 0x0003
}   MLBMAILBOX_SYSCONFIGSIdleModeE;

typedef enum {
    MLBMAILBOX_SYSCONFIGSoftResetb0 = 0x0000,
    MLBMAILBOX_SYSCONFIGSoftResetb1 = 0x0001
}   MLBMAILBOX_SYSCONFIGSoftResetE;

typedef enum {
    MLBMAILBOX_SYSCONFIGAutoIdleb0 = 0x0000,
    MLBMAILBOX_SYSCONFIGAutoIdleb1 = 0x0001
}   MLBMAILBOX_SYSCONFIGAutoIdleE;

typedef enum {
    MLBMAILBOX_SYSSTATUSResetDonerstongoing = 0x0000,
    MLBMAILBOX_SYSSTATUSResetDonerstcomp = 0x0001
}   MLBMAILBOX_SYSSTATUSResetDoneE;

/*****************************************************************************
* EXPORTED VARIABLES
******************************************************************************
*/

/*****************************************************************************
* EXPORTED FUNCTIONS
******************************************************************************
*/

#if defined(__cplusplus)
}	/* End of C++ extern block */
#endif /* defined(__cplusplus) */

#endif /* _MLB_ACC_INT_H */
/* EOF */

