/*
 * dspbridge/src/hal/common/mmu/MMUAccInt.h
 *
 * DSP-BIOS Bridge driver support functions for TI OMAP processors.
 *
 * Copyright (C) 2007 Texas Instruments, Inc.
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * THIS PACKAGE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */


#ifndef _MMU_ACC_INT_H
#define _MMU_ACC_INT_H

#if defined(__cplusplus)
extern "C" {
#endif  /* defined(__cplusplus) */


/**************************************************************************
* EXPORTED DEFINITIONS
***************************************************************************
*/

/* Mappings of level 1 EASI function numbers to function names */

#define EASIL1_MMUMMU_REVISIONReadRegister32 MMU_BASE_EASIL1 + 0
#define EASIL1_MMUMMU_REVISIONRevRead32  MMU_BASE_EASIL1 + 1
#define EASIL1_MMUMMU_REVISIONRevGet32 MMU_BASE_EASIL1 + 2
#define EASIL1_MMUMMU_SYSCONFIGReadRegister32 MMU_BASE_EASIL1 + 3
#define EASIL1_MMUMMU_SYSCONFIGWriteRegister32  MMU_BASE_EASIL1 + 4
#define EASIL1_MMUMMU_SYSCONFIGClockActivityRead32 MMU_BASE_EASIL1 + 5
#define EASIL1_MMUMMU_SYSCONFIGClockActivityGet32 MMU_BASE_EASIL1 + 6
#define EASIL1_MMUMMU_SYSCONFIGIdleModeRead32 MMU_BASE_EASIL1 + 7
#define EASIL1_MMUMMU_SYSCONFIGIdleModeReadIsSfIdle32 MMU_BASE_EASIL1 + 8
#define EASIL1_MMUMMU_SYSCONFIGIdleModeReadIsSnIdle32  MMU_BASE_EASIL1 + 9
#define EASIL1_MMUMMU_SYSCONFIGIdleModeReadIsSsIdle32 MMU_BASE_EASIL1 + 10
#define EASIL1_MMUMMU_SYSCONFIGIdleModeReadIsRes32 MMU_BASE_EASIL1 + 11
#define EASIL1_MMUMMU_SYSCONFIGIdleModeGet32 MMU_BASE_EASIL1 + 12
#define EASIL1_MMUMMU_SYSCONFIGIdleModeIsSfIdle32 MMU_BASE_EASIL1 + 13
#define EASIL1_MMUMMU_SYSCONFIGIdleModeIsSnIdle32 MMU_BASE_EASIL1 + 14
#define EASIL1_MMUMMU_SYSCONFIGIdleModeIsSsIdle32 MMU_BASE_EASIL1 + 15
#define EASIL1_MMUMMU_SYSCONFIGIdleModeIsRes32  MMU_BASE_EASIL1 + 16
#define EASIL1_MMUMMU_SYSCONFIGIdleModeWrite32  MMU_BASE_EASIL1 + 17
#define EASIL1_MMUMMU_SYSCONFIGIdleModeWriteSfIdle32 MMU_BASE_EASIL1 + 18
#define EASIL1_MMUMMU_SYSCONFIGIdleModeWriteSnIdle32 MMU_BASE_EASIL1 + 19
#define EASIL1_MMUMMU_SYSCONFIGIdleModeWriteSsIdle32 MMU_BASE_EASIL1 + 20
#define EASIL1_MMUMMU_SYSCONFIGIdleModeWriteRes32 MMU_BASE_EASIL1 + 21
#define EASIL1_MMUMMU_SYSCONFIGIdleModeSet32  MMU_BASE_EASIL1 + 22
#define EASIL1_MMUMMU_SYSCONFIGSoftResetRead32 MMU_BASE_EASIL1 + 23
#define EASIL1_MMUMMU_SYSCONFIGSoftResetReadIsalways_r32 \
						MMU_BASE_EASIL1 + 24
#define EASIL1_MMUMMU_SYSCONFIGSoftResetReadIsnever_r32 \
						MMU_BASE_EASIL1 + 25
#define EASIL1_MMUMMU_SYSCONFIGSoftResetGet32   MMU_BASE_EASIL1 + 26
#define EASIL1_MMUMMU_SYSCONFIGSoftResetIsalways_r32 MMU_BASE_EASIL1 + 27
#define EASIL1_MMUMMU_SYSCONFIGSoftResetIsnever_r32 MMU_BASE_EASIL1 + 28
#define EASIL1_MMUMMU_SYSCONFIGSoftResetWrite32 MMU_BASE_EASIL1 + 29
#define EASIL1_MMUMMU_SYSCONFIGSoftResetWritenofun_w32 MMU_BASE_EASIL1 + 30
#define EASIL1_MMUMMU_SYSCONFIGSoftResetWriterstMode_w32\
						MMU_BASE_EASIL1 + 31
#define EASIL1_MMUMMU_SYSCONFIGSoftResetSet32  MMU_BASE_EASIL1 + 32
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleRead32  MMU_BASE_EASIL1 + 33
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleReadIsclkfree32 MMU_BASE_EASIL1 + 34
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleReadIsautoClkGate32\
						MMU_BASE_EASIL1 + 35
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleGet32 MMU_BASE_EASIL1 + 36
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleIsclkfree32   MMU_BASE_EASIL1 + 37
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleIsautoClkGate32 MMU_BASE_EASIL1 + 38
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleWrite32    MMU_BASE_EASIL1 + 39
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleWriteclkfree32 MMU_BASE_EASIL1 + 40
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleWriteautoClkGate32 \
						MMU_BASE_EASIL1 + 41
#define EASIL1_MMUMMU_SYSCONFIGAutoIdleSet32   MMU_BASE_EASIL1 + 42
#define EASIL1_MMUMMU_SYSSTATUSReadRegister32   MMU_BASE_EASIL1 + 43
#define EASIL1_MMUMMU_SYSSTATUSResetDoneRead32   MMU_BASE_EASIL1 + 44
#define EASIL1_MMUMMU_SYSSTATUSResetDoneReadIsrstongoing32   \
						MMU_BASE_EASIL1 + 45
#define EASIL1_MMUMMU_SYSSTATUSResetDoneReadIsrstcomp32 \
						MMU_BASE_EASIL1 + 46
#define EASIL1_MMUMMU_SYSSTATUSResetDoneGet32      MMU_BASE_EASIL1 + 47
#define EASIL1_MMUMMU_SYSSTATUSResetDoneIsrstongoing32 MMU_BASE_EASIL1 + 48
#define EASIL1_MMUMMU_SYSSTATUSResetDoneIsrstcomp32 MMU_BASE_EASIL1 + 49
#define EASIL1_MMUMMU_IRQSTATUSReadRegister32    MMU_BASE_EASIL1 + 50
#define EASIL1_MMUMMU_IRQSTATUSWriteRegister32   MMU_BASE_EASIL1 + 51
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultRead32   MMU_BASE_EASIL1 + 52
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultReadIsnMHF_r32 \
						MMU_BASE_EASIL1 + 53
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultReadIsMHF_r32\
						MMU_BASE_EASIL1 + 54
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultGet32  MMU_BASE_EASIL1 + 55
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultIsnMHF_r32 \
						MMU_BASE_EASIL1 + 56
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultIsMHF_r32 MMU_BASE_EASIL1 + 57
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultWrite32  MMU_BASE_EASIL1 + 58
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultWriteMHFstat_w32\
						MMU_BASE_EASIL1 + 59
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultWriterMHFstat_w32 \
						MMU_BASE_EASIL1 + 60
#define EASIL1_MMUMMU_IRQSTATUSMultiHitFaultSet32    MMU_BASE_EASIL1 + 61
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultRead32 MMU_BASE_EASIL1 + 62
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultReadIsnTWF_r32\
						MMU_BASE_EASIL1 + 63
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultReadIsTWF_r32\
						MMU_BASE_EASIL1 + 64
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultGet32  MMU_BASE_EASIL1 + 65
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultIsnTWF_r32\
						MMU_BASE_EASIL1 + 66
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultIsTWF_r32 MMU_BASE_EASIL1 + 67
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultWrite32  MMU_BASE_EASIL1 + 68
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultWriteTWFstat_w32\
						MMU_BASE_EASIL1 + 69
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultWriterTWFstat_w32\
						MMU_BASE_EASIL1 + 70
#define EASIL1_MMUMMU_IRQSTATUSTableWalkFaultSet32  MMU_BASE_EASIL1 + 71
#define EASIL1_MMUMMU_IRQSTATUSEMUMissRead32    MMU_BASE_EASIL1 + 72
#define EASIL1_MMUMMU_IRQSTATUSEMUMissReadIsnEMUM_r32 MMU_BASE_EASIL1 + 73
#define EASIL1_MMUMMU_IRQSTATUSEMUMissReadIsEMUM_r32 MMU_BASE_EASIL1 + 74
#define EASIL1_MMUMMU_IRQSTATUSEMUMissGet32    MMU_BASE_EASIL1 + 75
#define EASIL1_MMUMMU_IRQSTATUSEMUMissIsnEMUM_r32   MMU_BASE_EASIL1 + 76
#define EASIL1_MMUMMU_IRQSTATUSEMUMissIsEMUM_r32 MMU_BASE_EASIL1 + 77
#define EASIL1_MMUMMU_IRQSTATUSEMUMissWrite32 MMU_BASE_EASIL1 + 78
#define EASIL1_MMUMMU_IRQSTATUSEMUMissWriteEstat_w32 MMU_BASE_EASIL1 + 79
#define EASIL1_MMUMMU_IRQSTATUSEMUMissWriterEstat_w32 MMU_BASE_EASIL1 + 80
#define EASIL1_MMUMMU_IRQSTATUSEMUMissSet32      MMU_BASE_EASIL1 + 81
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultRead32 MMU_BASE_EASIL1 + 82
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultReadIsnFault_r32 \
						MMU_BASE_EASIL1 + 83
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultReadIsFault_r32\
						MMU_BASE_EASIL1 + 84
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultGet32 MMU_BASE_EASIL1 + 85
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultIsnFault_r32 \
						MMU_BASE_EASIL1 + 86
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultIsFault_r32 \
						MMU_BASE_EASIL1 + 87
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultWrite32 MMU_BASE_EASIL1 + 88
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultWriteFstat_w32 \
						MMU_BASE_EASIL1 + 89
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultWriterFstat_w32  \
						MMU_BASE_EASIL1 + 90
#define EASIL1_MMUMMU_IRQSTATUSTranslationFaultSet32  MMU_BASE_EASIL1 + 91
#define EASIL1_MMUMMU_IRQSTATUSTLBMissRead32 MMU_BASE_EASIL1 + 92
#define EASIL1_MMUMMU_IRQSTATUSTLBMissReadIsnTLBM_r32 MMU_BASE_EASIL1 + 93
#define EASIL1_MMUMMU_IRQSTATUSTLBMissReadIsTLBM_r32 MMU_BASE_EASIL1 + 94
#define EASIL1_MMUMMU_IRQSTATUSTLBMissGet32 MMU_BASE_EASIL1 + 95
#define EASIL1_MMUMMU_IRQSTATUSTLBMissIsnTLBM_r32 MMU_BASE_EASIL1 + 96
#define EASIL1_MMUMMU_IRQSTATUSTLBMissIsTLBM_r32 MMU_BASE_EASIL1 + 97
#define EASIL1_MMUMMU_IRQSTATUSTLBMissWrite32 MMU_BASE_EASIL1 + 98
#define EASIL1_MMUMMU_IRQSTATUSTLBMissWriteMstat_w32 MMU_BASE_EASIL1 + 99
#define EASIL1_MMUMMU_IRQSTATUSTLBMissWriterMstat_w32 MMU_BASE_EASIL1 + 100
#define EASIL1_MMUMMU_IRQSTATUSTLBMissSet32 MMU_BASE_EASIL1 + 101
#define EASIL1_MMUMMU_IRQENABLEReadRegister32 MMU_BASE_EASIL1 + 102
#define EASIL1_MMUMMU_IRQENABLEWriteRegister32 MMU_BASE_EASIL1 + 103
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultRead32 MMU_BASE_EASIL1 + 104
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultReadIsMHFltMAsk32\
						MMU_BASE_EASIL1 + 105
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultReadIsMHFltGInt32  \
						MMU_BASE_EASIL1 + 106
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultGet32  MMU_BASE_EASIL1 + 107
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultIsMHFltMAsk32 \
						MMU_BASE_EASIL1 + 108
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultIsMHFltGInt32 \
						MMU_BASE_EASIL1 + 109
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultWrite32 MMU_BASE_EASIL1 + 110
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultWriteMHFltMAsk32\
						MMU_BASE_EASIL1 + 111
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultWriteMHFltGInt32\
						MMU_BASE_EASIL1 + 112
#define EASIL1_MMUMMU_IRQENABLEMultiHitFaultSet32 MMU_BASE_EASIL1 + 113
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultRead32 MMU_BASE_EASIL1 + 114
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultReadIsTWLFltMAsk32 \
						MMU_BASE_EASIL1 + 115
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultReadIsTWLFltGInt32  \
						MMU_BASE_EASIL1 + 116
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultGet32 MMU_BASE_EASIL1 + 117
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultIsTWLFltMAsk32\
						MMU_BASE_EASIL1 + 118
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultIsTWLFltGInt32 \
						MMU_BASE_EASIL1 + 119
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultWrite32 MMU_BASE_EASIL1 + 120
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultWriteTWLFltMAsk32\
						MMU_BASE_EASIL1 + 121
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultWriteTWLFltGInt32\
						MMU_BASE_EASIL1 + 122
#define EASIL1_MMUMMU_IRQENABLETableWalkFaultSet32 MMU_BASE_EASIL1 + 123
#define EASIL1_MMUMMU_IRQENABLEEMUMissRead32 MMU_BASE_EASIL1 + 124
#define EASIL1_MMUMMU_IRQENABLEEMUMissReadIsEMUMFltMask32\
						MMU_BASE_EASIL1 + 125
#define EASIL1_MMUMMU_IRQENABLEEMUMissReadIsEMUMFltGInt32\
						MMU_BASE_EASIL1 + 126
#define EASIL1_MMUMMU_IRQENABLEEMUMissGet32 MMU_BASE_EASIL1 + 127
#define EASIL1_MMUMMU_IRQENABLEEMUMissIsEMUMFltMask32 MMU_BASE_EASIL1 + 128
#define EASIL1_MMUMMU_IRQENABLEEMUMissIsEMUMFltGInt32 MMU_BASE_EASIL1 + 129
#define EASIL1_MMUMMU_IRQENABLEEMUMissWrite32 MMU_BASE_EASIL1 + 130
#define EASIL1_MMUMMU_IRQENABLEEMUMissWriteEMUMFltMask32\
						MMU_BASE_EASIL1 + 131
#define EASIL1_MMUMMU_IRQENABLEEMUMissWriteEMUMFltGInt32 \
						MMU_BASE_EASIL1 + 132
#define EASIL1_MMUMMU_IRQENABLEEMUMissSet32 MMU_BASE_EASIL1 + 133
#define EASIL1_MMUMMU_IRQENABLETranslationFaultRead32 MMU_BASE_EASIL1 + 134
#define EASIL1_MMUMMU_IRQENABLETranslationFaultReadIsTranFltMask3\
						MMU_BASE_EASIL1 + 135
#define EASIL1_MMUMMU_IRQENABLETranslationFaultReadIsTranFltGInt32\
						MMU_BASE_EASIL1 + 136
#define EASIL1_MMUMMU_IRQENABLETranslationFaultGet32 MMU_BASE_EASIL1 + 137
#define EASIL1_MMUMMU_IRQENABLETranslationFaultIsTranFltMask32\
						MMU_BASE_EASIL1 + 138
#define EASIL1_MMUMMU_IRQENABLETranslationFaultIsTranFltGInt32 \
						MMU_BASE_EASIL1 + 139
#define EASIL1_MMUMMU_IRQENABLETranslationFaultWrite32\
						MMU_BASE_EASIL1 + 140
#define EASIL1_MMUMMU_IRQENABLETranslationFaultWriteTranFltMask32\
						MMU_BASE_EASIL1 + 141
#define EASIL1_MMUMMU_IRQENABLETranslationFaultWriteTranFltGInt32  \
						MMU_BASE_EASIL1 + 142
#define EASIL1_MMUMMU_IRQENABLETranslationFaultSet32 MMU_BASE_EASIL1 + 143
#define EASIL1_MMUMMU_IRQENABLETLBMissRead32 MMU_BASE_EASIL1 + 144
#define EASIL1_MMUMMU_IRQENABLETLBMissReadIsTrMissIntM32 \
						MMU_BASE_EASIL1 + 145
#define EASIL1_MMUMMU_IRQENABLETLBMissReadIsTrMissGInt32 \
						MMU_BASE_EASIL1 + 146
#define EASIL1_MMUMMU_IRQENABLETLBMissGet32 MMU_BASE_EASIL1 + 147
#define EASIL1_MMUMMU_IRQENABLETLBMissIsTrMissIntM32 MMU_BASE_EASIL1 + 148
#define EASIL1_MMUMMU_IRQENABLETLBMissIsTrMissGInt32 MMU_BASE_EASIL1 + 149
#define EASIL1_MMUMMU_IRQENABLETLBMissWrite32 MMU_BASE_EASIL1 + 150
#define EASIL1_MMUMMU_IRQENABLETLBMissWriteTrMissIntM32 \
						MMU_BASE_EASIL1 + 151
#define EASIL1_MMUMMU_IRQENABLETLBMissWriteTrMissGInt32 \
						MMU_BASE_EASIL1 + 152
#define EASIL1_MMUMMU_IRQENABLETLBMissSet32 MMU_BASE_EASIL1 + 153
#define EASIL1_MMUMMU_WALKING_STReadRegister32 MMU_BASE_EASIL1 + 154
#define EASIL1_MMUMMU_WALKING_STWriteRegister32 MMU_BASE_EASIL1 + 155
#define EASIL1_MMUMMU_WALKING_STTWLRunningRead32 MMU_BASE_EASIL1 + 156
#define EASIL1_MMUMMU_WALKING_STTWLRunningReadIsTWLComp32 \
						MMU_BASE_EASIL1 + 157
#define EASIL1_MMUMMU_WALKING_STTWLRunningReadIsTWLRun32 \
						MMU_BASE_EASIL1 + 158
#define EASIL1_MMUMMU_WALKING_STTWLRunningGet32 MMU_BASE_EASIL1 + 159
#define EASIL1_MMUMMU_WALKING_STTWLRunningIsTWLComp32 MMU_BASE_EASIL1 + 160
#define EASIL1_MMUMMU_WALKING_STTWLRunningIsTWLRun32 MMU_BASE_EASIL1 + 161
#define EASIL1_MMUMMU_CNTLReadRegister32 MMU_BASE_EASIL1 + 162
#define EASIL1_MMUMMU_CNTLWriteRegister32 MMU_BASE_EASIL1 + 163
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateRead32 MMU_BASE_EASIL1 + 164
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateReadIsEMUdis32 MMU_BASE_EASIL1 + 165
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateReadIsEMUen32 MMU_BASE_EASIL1 + 166
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateGet32 MMU_BASE_EASIL1 + 167
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateIsEMUdis32 MMU_BASE_EASIL1 + 168
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateIsEMUen32 MMU_BASE_EASIL1 + 169
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateWrite32 MMU_BASE_EASIL1 + 170
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateWriteEMUdis32 MMU_BASE_EASIL1 + 171
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateWriteEMUen32 MMU_BASE_EASIL1 + 172
#define EASIL1_MMUMMU_CNTLEmuTLBUpdateSet32 MMU_BASE_EASIL1 + 173
#define EASIL1_MMUMMU_CNTLTWLEnableRead32 MMU_BASE_EASIL1 + 174
#define EASIL1_MMUMMU_CNTLTWLEnableReadIsTWLdis32 MMU_BASE_EASIL1 + 175
#define EASIL1_MMUMMU_CNTLTWLEnableReadIsTWLen32 MMU_BASE_EASIL1 + 176
#define EASIL1_MMUMMU_CNTLTWLEnableGet32 MMU_BASE_EASIL1 + 177
#define EASIL1_MMUMMU_CNTLTWLEnableIsTWLdis32  MMU_BASE_EASIL1 + 178
#define EASIL1_MMUMMU_CNTLTWLEnableIsTWLen32  MMU_BASE_EASIL1 + 179
#define EASIL1_MMUMMU_CNTLTWLEnableWrite32   MMU_BASE_EASIL1 + 180
#define EASIL1_MMUMMU_CNTLTWLEnableWriteTWLdis32  MMU_BASE_EASIL1 + 181
#define EASIL1_MMUMMU_CNTLTWLEnableWriteTWLen32   MMU_BASE_EASIL1 + 182
#define EASIL1_MMUMMU_CNTLTWLEnableSet32  MMU_BASE_EASIL1 + 183
#define EASIL1_MMUMMU_CNTLMMUEnableRead32 MMU_BASE_EASIL1 + 184
#define EASIL1_MMUMMU_CNTLMMUEnableReadIsMMUdis32   MMU_BASE_EASIL1 + 185
#define EASIL1_MMUMMU_CNTLMMUEnableReadIsMMUen32  MMU_BASE_EASIL1 + 186
#define EASIL1_MMUMMU_CNTLMMUEnableGet32  MMU_BASE_EASIL1 + 187
#define EASIL1_MMUMMU_CNTLMMUEnableIsMMUdis32     MMU_BASE_EASIL1 + 188
#define EASIL1_MMUMMU_CNTLMMUEnableIsMMUen32    MMU_BASE_EASIL1 + 189
#define EASIL1_MMUMMU_CNTLMMUEnableWrite32     MMU_BASE_EASIL1 + 190
#define EASIL1_MMUMMU_CNTLMMUEnableWriteMMUdis32 MMU_BASE_EASIL1 + 191
#define EASIL1_MMUMMU_CNTLMMUEnableWriteMMUen32 MMU_BASE_EASIL1 + 192
#define EASIL1_MMUMMU_CNTLMMUEnableSet32     MMU_BASE_EASIL1 + 193
#define EASIL1_MMUMMU_FAULT_ADReadRegister32   MMU_BASE_EASIL1 + 194
#define EASIL1_MMUMMU_FAULT_ADFaultAddressRead32   MMU_BASE_EASIL1 + 195
#define EASIL1_MMUMMU_FAULT_ADFaultAddressGet32  MMU_BASE_EASIL1 + 196
#define EASIL1_MMUMMU_TTBReadRegister32     MMU_BASE_EASIL1 + 197
#define EASIL1_MMUMMU_TTBWriteRegister32  MMU_BASE_EASIL1 + 198
#define EASIL1_MMUMMU_TTBTTBAddressRead32  MMU_BASE_EASIL1 + 199
#define EASIL1_MMUMMU_TTBTTBAddressGet32   MMU_BASE_EASIL1 + 200
#define EASIL1_MMUMMU_TTBTTBAddressWrite32  MMU_BASE_EASIL1 + 201
#define EASIL1_MMUMMU_TTBTTBAddressSet32   MMU_BASE_EASIL1 + 202
#define EASIL1_MMUMMU_LOCKReadRegister32   MMU_BASE_EASIL1 + 203
#define EASIL1_MMUMMU_LOCKWriteRegister32  MMU_BASE_EASIL1 + 204
#define EASIL1_MMUMMU_LOCKBaseValueRead32  MMU_BASE_EASIL1 + 205
#define EASIL1_MMUMMU_LOCKBaseValueGet32  MMU_BASE_EASIL1 + 206
#define EASIL1_MMUMMU_LOCKBaseValueWrite32   MMU_BASE_EASIL1 + 207
#define EASIL1_MMUMMU_LOCKBaseValueSet32    MMU_BASE_EASIL1 + 208
#define EASIL1_MMUMMU_LOCKCurrentVictimRead32 MMU_BASE_EASIL1 + 209
#define EASIL1_MMUMMU_LOCKCurrentVictimGet32 MMU_BASE_EASIL1 + 210
#define EASIL1_MMUMMU_LOCKCurrentVictimWrite32 MMU_BASE_EASIL1 + 211
#define EASIL1_MMUMMU_LOCKCurrentVictimSet32  MMU_BASE_EASIL1 + 212
#define EASIL1_MMUMMU_LD_TLBReadRegister32    MMU_BASE_EASIL1 + 213
#define EASIL1_MMUMMU_LD_TLBWriteRegister32   MMU_BASE_EASIL1 + 214
#define EASIL1_MMUMMU_LD_TLBLdTLBItemRead32   MMU_BASE_EASIL1 + 215
#define EASIL1_MMUMMU_LD_TLBLdTLBItemReadIsalways_r32 MMU_BASE_EASIL1 + 216
#define EASIL1_MMUMMU_LD_TLBLdTLBItemReadIsnever_r32 MMU_BASE_EASIL1 + 217
#define EASIL1_MMUMMU_LD_TLBLdTLBItemGet32 MMU_BASE_EASIL1 + 218
#define EASIL1_MMUMMU_LD_TLBLdTLBItemIsalways_r32 MMU_BASE_EASIL1 + 219
#define EASIL1_MMUMMU_LD_TLBLdTLBItemIsnever_r32 MMU_BASE_EASIL1 + 220
#define EASIL1_MMUMMU_LD_TLBLdTLBItemWrite32  MMU_BASE_EASIL1 + 221
#define EASIL1_MMUMMU_LD_TLBLdTLBItemWritenoeffect_w32 \
						MMU_BASE_EASIL1 + 222
#define EASIL1_MMUMMU_LD_TLBLdTLBItemWriteldTLB_w32 MMU_BASE_EASIL1 + 223
#define EASIL1_MMUMMU_LD_TLBLdTLBItemSet32 MMU_BASE_EASIL1 + 224
#define EASIL1_MMUMMU_CAMReadRegister32    MMU_BASE_EASIL1 + 225
#define EASIL1_MMUMMU_CAMWriteRegister32   MMU_BASE_EASIL1 + 226
#define EASIL1_MMUMMU_CAMVATagRead32      MMU_BASE_EASIL1 + 227
#define EASIL1_MMUMMU_CAMVATagGet32   MMU_BASE_EASIL1 + 228
#define EASIL1_MMUMMU_CAMVATagWrite32  MMU_BASE_EASIL1 + 229
#define EASIL1_MMUMMU_CAMVATagSet32 MMU_BASE_EASIL1 + 230
#define EASIL1_MMUMMU_CAMPRead32       MMU_BASE_EASIL1 + 231
#define EASIL1_MMUMMU_CAMPReadIsCanFlush32  MMU_BASE_EASIL1 + 232
#define EASIL1_MMUMMU_CAMPReadIsNoFlush32   MMU_BASE_EASIL1 + 233
#define EASIL1_MMUMMU_CAMPGet32     MMU_BASE_EASIL1 + 234
#define EASIL1_MMUMMU_CAMPIsCanFlush32   MMU_BASE_EASIL1 + 235
#define EASIL1_MMUMMU_CAMPIsNoFlush32  MMU_BASE_EASIL1 + 236
#define EASIL1_MMUMMU_CAMPWrite32  MMU_BASE_EASIL1 + 237
#define EASIL1_MMUMMU_CAMPWriteCanFlush32  MMU_BASE_EASIL1 + 238
#define EASIL1_MMUMMU_CAMPWriteNoFlush32 MMU_BASE_EASIL1 + 239
#define EASIL1_MMUMMU_CAMPSet32 MMU_BASE_EASIL1 + 240
#define EASIL1_MMUMMU_CAMVRead32 MMU_BASE_EASIL1 + 241
#define EASIL1_MMUMMU_CAMVReadIsInvalid32  MMU_BASE_EASIL1 + 242
#define EASIL1_MMUMMU_CAMVReadIsValid32  MMU_BASE_EASIL1 + 243
#define EASIL1_MMUMMU_CAMVGet32  MMU_BASE_EASIL1 + 244
#define EASIL1_MMUMMU_CAMVIsInvalid32  MMU_BASE_EASIL1 + 245
#define EASIL1_MMUMMU_CAMVIsValid32  MMU_BASE_EASIL1 + 246
#define EASIL1_MMUMMU_CAMVWrite32   MMU_BASE_EASIL1 + 247
#define EASIL1_MMUMMU_CAMVWriteInvalid32  MMU_BASE_EASIL1 + 248
#define EASIL1_MMUMMU_CAMVWriteValid32     MMU_BASE_EASIL1 + 249
#define EASIL1_MMUMMU_CAMVSet32   MMU_BASE_EASIL1 + 250
#define EASIL1_MMUMMU_CAMPageSizeRead32   MMU_BASE_EASIL1 + 251
#define EASIL1_MMUMMU_CAMPageSizeReadIsSection32  MMU_BASE_EASIL1 + 252
#define EASIL1_MMUMMU_CAMPageSizeReadIsLarge32 MMU_BASE_EASIL1 + 253
#define EASIL1_MMUMMU_CAMPageSizeReadIsSmall32 MMU_BASE_EASIL1 + 254
#define EASIL1_MMUMMU_CAMPageSizeReadIsSuper32 MMU_BASE_EASIL1 + 255
#define EASIL1_MMUMMU_CAMPageSizeGet32  MMU_BASE_EASIL1 + 256
#define EASIL1_MMUMMU_CAMPageSizeIsSection32  MMU_BASE_EASIL1 + 257
#define EASIL1_MMUMMU_CAMPageSizeIsLarge32  MMU_BASE_EASIL1 + 258
#define EASIL1_MMUMMU_CAMPageSizeIsSmall32 MMU_BASE_EASIL1 + 259
#define EASIL1_MMUMMU_CAMPageSizeIsSuper32  MMU_BASE_EASIL1 + 260
#define EASIL1_MMUMMU_CAMPageSizeWrite32   MMU_BASE_EASIL1 + 261
#define EASIL1_MMUMMU_CAMPageSizeWriteSection32  MMU_BASE_EASIL1 + 262
#define EASIL1_MMUMMU_CAMPageSizeWriteLarge32 MMU_BASE_EASIL1 + 263
#define EASIL1_MMUMMU_CAMPageSizeWriteSmall32  MMU_BASE_EASIL1 + 264
#define EASIL1_MMUMMU_CAMPageSizeWriteSuper32   MMU_BASE_EASIL1 + 265
#define EASIL1_MMUMMU_CAMPageSizeSet32    MMU_BASE_EASIL1 + 266
#define EASIL1_MMUMMU_RAMReadRegister32  MMU_BASE_EASIL1 + 267
#define EASIL1_MMUMMU_RAMWriteRegister32 MMU_BASE_EASIL1 + 268
#define EASIL1_MMUMMU_RAMPhysicalAddressRead32  MMU_BASE_EASIL1 + 269
#define EASIL1_MMUMMU_RAMPhysicalAddressGet32 MMU_BASE_EASIL1 + 270
#define EASIL1_MMUMMU_RAMPhysicalAddressWrite32  MMU_BASE_EASIL1 + 271
#define EASIL1_MMUMMU_RAMPhysicalAddressSet32  MMU_BASE_EASIL1 + 272
#define EASIL1_MMUMMU_RAMEndiannessRead32   MMU_BASE_EASIL1 + 273
#define EASIL1_MMUMMU_RAMEndiannessReadIsLittle32  MMU_BASE_EASIL1 + 274
#define EASIL1_MMUMMU_RAMEndiannessReadIsBig32 MMU_BASE_EASIL1 + 275
#define EASIL1_MMUMMU_RAMEndiannessGet32  MMU_BASE_EASIL1 + 276
#define EASIL1_MMUMMU_RAMEndiannessIsLittle32  MMU_BASE_EASIL1 + 277
#define EASIL1_MMUMMU_RAMEndiannessIsBig32   MMU_BASE_EASIL1 + 278
#define EASIL1_MMUMMU_RAMEndiannessWrite32  MMU_BASE_EASIL1 + 279
#define EASIL1_MMUMMU_RAMEndiannessWriteLittle32  MMU_BASE_EASIL1 + 280
#define EASIL1_MMUMMU_RAMEndiannessWriteBig32  MMU_BASE_EASIL1 + 281
#define EASIL1_MMUMMU_RAMEndiannessSet32   MMU_BASE_EASIL1 + 282
#define EASIL1_MMUMMU_RAMElementSizeRead32    MMU_BASE_EASIL1 + 283
#define EASIL1_MMUMMU_RAMElementSizeReadIsByte32   MMU_BASE_EASIL1 + 284
#define EASIL1_MMUMMU_RAMElementSizeReadIsShort32  MMU_BASE_EASIL1 + 285
#define EASIL1_MMUMMU_RAMElementSizeReadIsLong32  MMU_BASE_EASIL1 + 286
#define EASIL1_MMUMMU_RAMElementSizeReadIsNone32  MMU_BASE_EASIL1 + 287
#define EASIL1_MMUMMU_RAMElementSizeGet32   MMU_BASE_EASIL1 + 288
#define EASIL1_MMUMMU_RAMElementSizeIsByte32  MMU_BASE_EASIL1 + 289
#define EASIL1_MMUMMU_RAMElementSizeIsShort32  MMU_BASE_EASIL1 + 290
#define EASIL1_MMUMMU_RAMElementSizeIsLong32  MMU_BASE_EASIL1 + 291
#define EASIL1_MMUMMU_RAMElementSizeIsNone32  MMU_BASE_EASIL1 + 292
#define EASIL1_MMUMMU_RAMElementSizeWrite32   MMU_BASE_EASIL1 + 293
#define EASIL1_MMUMMU_RAMElementSizeWriteByte32 MMU_BASE_EASIL1 + 294
#define EASIL1_MMUMMU_RAMElementSizeWriteShort32 MMU_BASE_EASIL1 + 295
#define EASIL1_MMUMMU_RAMElementSizeWriteLong32  MMU_BASE_EASIL1 + 296
#define EASIL1_MMUMMU_RAMElementSizeWriteNone32  MMU_BASE_EASIL1 + 297
#define EASIL1_MMUMMU_RAMElementSizeSet32  MMU_BASE_EASIL1 + 298
#define EASIL1_MMUMMU_RAMMixedRead32 MMU_BASE_EASIL1 + 299
#define EASIL1_MMUMMU_RAMMixedReadIsTLBes32  MMU_BASE_EASIL1 + 300
#define EASIL1_MMUMMU_RAMMixedReadIsCPUes32 MMU_BASE_EASIL1 + 301
#define EASIL1_MMUMMU_RAMMixedGet32  MMU_BASE_EASIL1 + 302
#define EASIL1_MMUMMU_RAMMixedIsTLBes32  MMU_BASE_EASIL1 + 303
#define EASIL1_MMUMMU_RAMMixedIsCPUes32 MMU_BASE_EASIL1 + 304
#define EASIL1_MMUMMU_RAMMixedWrite32  MMU_BASE_EASIL1 + 305
#define EASIL1_MMUMMU_RAMMixedWriteTLBes32  MMU_BASE_EASIL1 + 306
#define EASIL1_MMUMMU_RAMMixedWriteCPUes32 MMU_BASE_EASIL1 + 307
#define EASIL1_MMUMMU_RAMMixedSet32  MMU_BASE_EASIL1 + 308
#define EASIL1_MMUMMU_GFLUSHReadRegister32   MMU_BASE_EASIL1 + 309
#define EASIL1_MMUMMU_GFLUSHWriteRegister32 MMU_BASE_EASIL1 + 310
#define EASIL1_MMUMMU_GFLUSHGlobalFlushRead32  MMU_BASE_EASIL1 + 311
#define EASIL1_MMUMMU_GFLUSHGlobalFlushReadIsrtn0_r32 MMU_BASE_EASIL1 + 312
#define EASIL1_MMUMMU_GFLUSHGlobalFlushReadIsnever_r3 \
						MMU_BASE_EASIL1 + 313
#define EASIL1_MMUMMU_GFLUSHGlobalFlushGet32 MMU_BASE_EASIL1 + 314
#define EASIL1_MMUMMU_GFLUSHGlobalFlushIsrtn0_r32 MMU_BASE_EASIL1 + 315
#define EASIL1_MMUMMU_GFLUSHGlobalFlushIsnever_r32 MMU_BASE_EASIL1 + 316
#define EASIL1_MMUMMU_GFLUSHGlobalFlushWrite32 MMU_BASE_EASIL1 + 317
#define EASIL1_MMUMMU_GFLUSHGlobalFlushWritenft_w32 MMU_BASE_EASIL1 + 318
#define EASIL1_MMUMMU_GFLUSHGlobalFlushWriteflush_w32 \
						MMU_BASE_EASIL1 + 319
#define EASIL1_MMUMMU_GFLUSHGlobalFlushSet32 MMU_BASE_EASIL1 + 320
#define EASIL1_MMUMMU_FLUSH_ENTRYReadRegister32 MMU_BASE_EASIL1 + 321
#define EASIL1_MMUMMU_FLUSH_ENTRYWriteRegister32  MMU_BASE_EASIL1 + 322
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryRead32 MMU_BASE_EASIL1 + 323
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryReadIsalways_r32  \
					MMU_BASE_EASIL1 + 324
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryReadIsnever_r32  \
						MMU_BASE_EASIL1 + 325
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryGet32 MMU_BASE_EASIL1 + 326
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryIsalways_r32 \
						MMU_BASE_EASIL1 + 327
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryIsnever_r32  \
						MMU_BASE_EASIL1 + 328
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryWrite32 MMU_BASE_EASIL1 + 329
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryWritenofun_w32   \
					MMU_BASE_EASIL1 + 330
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntryWriteflushTLB_w32 \
						MMU_BASE_EASIL1 + 331
#define EASIL1_MMUMMU_FLUSH_ENTRYFlushEntrySet32 MMU_BASE_EASIL1 + 332
#define EASIL1_MMUMMU_READ_CAMReadRegister32 MMU_BASE_EASIL1 + 333
#define EASIL1_MMUMMU_READ_CAMVATagRead32 MMU_BASE_EASIL1 + 334
#define EASIL1_MMUMMU_READ_CAMVATagGet32 MMU_BASE_EASIL1 + 335
#define EASIL1_MMUMMU_READ_CAMPRead32 MMU_BASE_EASIL1 + 336
#define EASIL1_MMUMMU_READ_CAMPReadIsCanFlush32 MMU_BASE_EASIL1 + 337
#define EASIL1_MMUMMU_READ_CAMPReadIsNoFlush32 MMU_BASE_EASIL1 + 338
#define EASIL1_MMUMMU_READ_CAMPGet32  MMU_BASE_EASIL1 + 339
#define EASIL1_MMUMMU_READ_CAMPIsCanFlush32 MMU_BASE_EASIL1 + 340
#define EASIL1_MMUMMU_READ_CAMPIsNoFlush32 MMU_BASE_EASIL1 + 341
#define EASIL1_MMUMMU_READ_CAMVRead32  MMU_BASE_EASIL1 + 342
#define EASIL1_MMUMMU_READ_CAMVReadIsInvalid32 MMU_BASE_EASIL1 + 343
#define EASIL1_MMUMMU_READ_CAMVReadIsValid32  MMU_BASE_EASIL1 + 344
#define EASIL1_MMUMMU_READ_CAMVGet32   MMU_BASE_EASIL1 + 345
#define EASIL1_MMUMMU_READ_CAMVIsInvalid32  MMU_BASE_EASIL1 + 346
#define EASIL1_MMUMMU_READ_CAMVIsValid32  MMU_BASE_EASIL1 + 347
#define EASIL1_MMUMMU_READ_CAMPageSizeRead32  MMU_BASE_EASIL1 + 348
#define EASIL1_MMUMMU_READ_CAMPageSizeReadIsSection32 MMU_BASE_EASIL1 + 349
#define EASIL1_MMUMMU_READ_CAMPageSizeReadIsLarge32 MMU_BASE_EASIL1 + 350
#define EASIL1_MMUMMU_READ_CAMPageSizeReadIsSmall32 MMU_BASE_EASIL1 + 351
#define EASIL1_MMUMMU_READ_CAMPageSizeReadIsSuper32 MMU_BASE_EASIL1 + 352
#define EASIL1_MMUMMU_READ_CAMPageSizeGet32  MMU_BASE_EASIL1 + 353
#define EASIL1_MMUMMU_READ_CAMPageSizeIsSection32 MMU_BASE_EASIL1 + 354
#define EASIL1_MMUMMU_READ_CAMPageSizeIsLarge32  MMU_BASE_EASIL1 + 355
#define EASIL1_MMUMMU_READ_CAMPageSizeIsSmall32 MMU_BASE_EASIL1 + 356
#define EASIL1_MMUMMU_READ_CAMPageSizeIsSuper32 MMU_BASE_EASIL1 + 357
#define EASIL1_MMUMMU_READ_RAMReadRegister32 MMU_BASE_EASIL1 + 358
#define EASIL1_MMUMMU_READ_RAMPhysicalAddressRead32 MMU_BASE_EASIL1 + 359
#define EASIL1_MMUMMU_READ_RAMPhysicalAddressGet32 MMU_BASE_EASIL1 + 360
#define EASIL1_MMUMMU_READ_RAMEndiannessRead32 MMU_BASE_EASIL1 + 361
#define EASIL1_MMUMMU_READ_RAMEndiannessReadIsLittle32 MMU_BASE_EASIL1 + 362
#define EASIL1_MMUMMU_READ_RAMEndiannessReadIsBig32 MMU_BASE_EASIL1 + 363
#define EASIL1_MMUMMU_READ_RAMEndiannessGet32  MMU_BASE_EASIL1 + 364
#define EASIL1_MMUMMU_READ_RAMEndiannessIsLittle32 MMU_BASE_EASIL1 + 365
#define EASIL1_MMUMMU_READ_RAMEndiannessIsBig32  MMU_BASE_EASIL1 + 366
#define EASIL1_MMUMMU_READ_RAMElementSizeRead32  MMU_BASE_EASIL1 + 367
#define EASIL1_MMUMMU_READ_RAMElementSizeReadIsByte32 MMU_BASE_EASIL1 + 368
#define EASIL1_MMUMMU_READ_RAMElementSizeReadIsShort32 \
						MMU_BASE_EASIL1 + 369
#define EASIL1_MMUMMU_READ_RAMElementSizeReadIsLong32 MMU_BASE_EASIL1 + 370
#define EASIL1_MMUMMU_READ_RAMElementSizeReadIsNone32 MMU_BASE_EASIL1 + 371
#define EASIL1_MMUMMU_READ_RAMElementSizeGet32 MMU_BASE_EASIL1 + 372
#define EASIL1_MMUMMU_READ_RAMElementSizeIsByte32 MMU_BASE_EASIL1 + 373
#define EASIL1_MMUMMU_READ_RAMElementSizeIsShort32  MMU_BASE_EASIL1 + 374
#define EASIL1_MMUMMU_READ_RAMElementSizeIsLong32 MMU_BASE_EASIL1 + 375
#define EASIL1_MMUMMU_READ_RAMElementSizeIsNone32 MMU_BASE_EASIL1 + 376
#define EASIL1_MMUMMU_READ_RAMMixedRead32  MMU_BASE_EASIL1 + 377
#define EASIL1_MMUMMU_READ_RAMMixedReadIsTLBes32  MMU_BASE_EASIL1 + 378
#define EASIL1_MMUMMU_READ_RAMMixedReadIsCPUes32 MMU_BASE_EASIL1 + 379
#define EASIL1_MMUMMU_READ_RAMMixedGet32 MMU_BASE_EASIL1 + 380
#define EASIL1_MMUMMU_READ_RAMMixedIsTLBes32   MMU_BASE_EASIL1 + 381
#define EASIL1_MMUMMU_READ_RAMMixedIsCPUes32   MMU_BASE_EASIL1 + 382
#define EASIL1_MMUMMU_EMU_FAULT_ADReadRegister32  MMU_BASE_EASIL1 + 383
#define EASIL1_MMUMMU_EMU_FAULT_ADEmuFaultAddressRead32 \
						MMU_BASE_EASIL1 + 384
#define EASIL1_MMUMMU_EMU_FAULT_ADEmuFaultAddressGet32 MMU_BASE_EASIL1 + 385
/* Register offset address definitions */
#define MMU_MMU_REVISION_OFFSET  0x0
#define MMU_MMU_SYSCONFIG_OFFSET   0x10
#define MMU_MMU_SYSSTATUS_OFFSET 0x14
#define MMU_MMU_IRQSTATUS_OFFSET  0x18
#define MMU_MMU_IRQENABLE_OFFSET    0x1c
#define MMU_MMU_WALKING_ST_OFFSET 0x40
#define MMU_MMU_CNTL_OFFSET   0x44
#define MMU_MMU_FAULT_AD_OFFSET  0x48
#define MMU_MMU_TTB_OFFSET  0x4c
#define MMU_MMU_LOCK_OFFSET   0x50
#define MMU_MMU_LD_TLB_OFFSET  0x54
#define MMU_MMU_CAM_OFFSET   0x58
#define MMU_MMU_RAM_OFFSET   0x5c
#define MMU_MMU_GFLUSH_OFFSET  0x60
#define MMU_MMU_FLUSH_ENTRY_OFFSET  0x64
#define MMU_MMU_READ_CAM_OFFSET  0x68
#define MMU_MMU_READ_RAM_OFFSET  0x6c
#define MMU_MMU_EMU_FAULT_AD_OFFSET   0x70
/* Bitfield mask and offset declarations */
#define MMU_MMU_REVISION_Rev_MASK   0xff
#define MMU_MMU_REVISION_Rev_OFFSET   0
#define MMU_MMU_SYSCONFIG_ClockActivity_MASK   0x300
#define MMU_MMU_SYSCONFIG_ClockActivity_OFFSET  8
#define MMU_MMU_SYSCONFIG_IdleMode_MASK  0x18
#define MMU_MMU_SYSCONFIG_IdleMode_OFFSET  3
#define MMU_MMU_SYSCONFIG_SoftReset_MASK  0x2
#define MMU_MMU_SYSCONFIG_SoftReset_OFFSET   1
#define MMU_MMU_SYSCONFIG_AutoIdle_MASK  0x1
#define MMU_MMU_SYSCONFIG_AutoIdle_OFFSET   0
#define MMU_MMU_SYSSTATUS_ResetDone_MASK  0x1
#define MMU_MMU_SYSSTATUS_ResetDone_OFFSET   0
#define MMU_MMU_IRQSTATUS_MultiHitFault_MASK  0x10
#define MMU_MMU_IRQSTATUS_MultiHitFault_OFFSET 4
#define MMU_MMU_IRQSTATUS_TableWalkFault_MASK  0x8
#define MMU_MMU_IRQSTATUS_TableWalkFault_OFFSET    3
#define MMU_MMU_IRQSTATUS_EMUMiss_MASK   0x4
#define MMU_MMU_IRQSTATUS_EMUMiss_OFFSET 2
#define MMU_MMU_IRQSTATUS_TranslationFault_MASK   0x2
#define MMU_MMU_IRQSTATUS_TranslationFault_OFFSET  1
#define MMU_MMU_IRQSTATUS_TLBMiss_MASK   0x1
#define MMU_MMU_IRQSTATUS_TLBMiss_OFFSET   0
#define MMU_MMU_IRQENABLE_MultiHitFault_MASK  0x10
#define MMU_MMU_IRQENABLE_MultiHitFault_OFFSET    4
#define MMU_MMU_IRQENABLE_TableWalkFault_MASK   0x8
#define MMU_MMU_IRQENABLE_TableWalkFault_OFFSET    3
#define MMU_MMU_IRQENABLE_EMUMiss_MASK       0x4
#define MMU_MMU_IRQENABLE_EMUMiss_OFFSET      2
#define MMU_MMU_IRQENABLE_TranslationFault_MASK 0x2
#define MMU_MMU_IRQENABLE_TranslationFault_OFFSET  1
#define MMU_MMU_IRQENABLE_TLBMiss_MASK   0x1
#define MMU_MMU_IRQENABLE_TLBMiss_OFFSET   0
#define MMU_MMU_WALKING_ST_TWLRunning_MASK 0x1
#define MMU_MMU_WALKING_ST_TWLRunning_OFFSET  0
#define MMU_MMU_CNTL_EmuTLBUpdate_MASK  0x8
#define MMU_MMU_CNTL_EmuTLBUpdate_OFFSET  3
#define MMU_MMU_CNTL_TWLEnable_MASK 0x4
#define MMU_MMU_CNTL_TWLEnable_OFFSET 2
#define MMU_MMU_CNTL_MMUEnable_MASK    0x2
#define MMU_MMU_CNTL_MMUEnable_OFFSET   1
#define MMU_MMU_FAULT_AD_FaultAddress_MASK   0xffffffff
#define MMU_MMU_FAULT_AD_FaultAddress_OFFSET   0
#define MMU_MMU_TTB_TTBAddress_MASK     0xffffff00
#define MMU_MMU_TTB_TTBAddress_OFFSET 8
#define MMU_MMU_LOCK_BaseValue_MASK 0xfc00
#define MMU_MMU_LOCK_BaseValue_OFFSET   10
#define MMU_MMU_LOCK_CurrentVictim_MASK   0x3f0
#define MMU_MMU_LOCK_CurrentVictim_OFFSET    4
#define MMU_MMU_LD_TLB_LdTLBItem_MASK  0x1
#define MMU_MMU_LD_TLB_LdTLBItem_OFFSET   0
#define MMU_MMU_CAM_VATag_MASK  0xfffff000
#define MMU_MMU_CAM_VATag_OFFSET  12
#define MMU_MMU_CAM_P_MASK  0x8
#define MMU_MMU_CAM_P_OFFSET  3
#define MMU_MMU_CAM_V_MASK  0x4
#define MMU_MMU_CAM_V_OFFSET  2
#define MMU_MMU_CAM_PageSize_MASK   0x3
#define MMU_MMU_CAM_PageSize_OFFSET  0
#define MMU_MMU_RAM_PhysicalAddress_MASK   0xfffff000
#define MMU_MMU_RAM_PhysicalAddress_OFFSET   12
#define MMU_MMU_RAM_Endianness_MASK 0x200
#define MMU_MMU_RAM_Endianness_OFFSET 9
#define MMU_MMU_RAM_ElementSize_MASK  0x180
#define MMU_MMU_RAM_ElementSize_OFFSET  7
#define MMU_MMU_RAM_Mixed_MASK  0x40
#define MMU_MMU_RAM_Mixed_OFFSET   6
#define MMU_MMU_GFLUSH_GlobalFlush_MASK 0x1
#define MMU_MMU_GFLUSH_GlobalFlush_OFFSET   0
#define MMU_MMU_FLUSH_ENTRY_FlushEntry_MASK  0x1
#define MMU_MMU_FLUSH_ENTRY_FlushEntry_OFFSET   0
#define MMU_MMU_READ_CAM_VATag_MASK 0xfffff000
#define MMU_MMU_READ_CAM_VATag_OFFSET  12
#define MMU_MMU_READ_CAM_P_MASK 0x8
#define MMU_MMU_READ_CAM_P_OFFSET   3
#define MMU_MMU_READ_CAM_V_MASK   0x4
#define MMU_MMU_READ_CAM_V_OFFSET     2
#define MMU_MMU_READ_CAM_PageSize_MASK   0x3
#define MMU_MMU_READ_CAM_PageSize_OFFSET    0
#define MMU_MMU_READ_RAM_PhysicalAddress_MASK  0xfffff000
#define MMU_MMU_READ_RAM_PhysicalAddress_OFFSET 12
#define MMU_MMU_READ_RAM_Endianness_MASK    0x200
#define MMU_MMU_READ_RAM_Endianness_OFFSET  9
#define MMU_MMU_READ_RAM_ElementSize_MASK   0x180
#define MMU_MMU_READ_RAM_ElementSize_OFFSET  7
#define MMU_MMU_READ_RAM_Mixed_MASK  0x40
#define MMU_MMU_READ_RAM_Mixed_OFFSET   6
#define MMU_MMU_EMU_FAULT_AD_EmuFaultAddress_MASK 0xffffffff
#define MMU_MMU_EMU_FAULT_AD_EmuFaultAddress_OFFSET  0

/**************************************************************************
* EXPORTED TYPE
**************************************************************************/

/* The following type definitions represent the enumerated values for
   each bitfield */

typedef enum {
    MMUMMU_SYSCONFIGIdleModeSfIdle = 0x0000,
    MMUMMU_SYSCONFIGIdleModeSnIdle = 0x0001,
    MMUMMU_SYSCONFIGIdleModeSsIdle = 0x0002,
    MMUMMU_SYSCONFIGIdleModeRes = 0x0003
}   MMUMMU_SYSCONFIGIdleModeE;

typedef enum {
    MMUMMU_SYSCONFIGSoftResetalways_r = 0x0000,
    MMUMMU_SYSCONFIGSoftResetnofun_w = 0x0000,
    MMUMMU_SYSCONFIGSoftResetnever_r = 0x0001,
    MMUMMU_SYSCONFIGSoftResetrstMode_w = 0x0001
}   MMUMMU_SYSCONFIGSoftResetE;

typedef enum {
    MMUMMU_SYSCONFIGAutoIdleclkfree = 0x0000,
    MMUMMU_SYSCONFIGAutoIdleautoClkGate = 0x0001
}   MMUMMU_SYSCONFIGAutoIdleE;

typedef enum {
    MMUMMU_SYSSTATUSResetDonerstongoing = 0x0000,
    MMUMMU_SYSSTATUSResetDonerstcomp = 0x0001
}   MMUMMU_SYSSTATUSResetDoneE;

typedef enum {
    MMUMMU_IRQSTATUSMultiHitFaultnMHF_r = 0x0000,
    MMUMMU_IRQSTATUSMultiHitFaultMHFstat_w = 0x0000,
    MMUMMU_IRQSTATUSMultiHitFaultMHF_r = 0x0001,
    MMUMMU_IRQSTATUSMultiHitFaultrMHFstat_w = 0x0001
}   MMUMMU_IRQSTATUSMultiHitFaultE;

typedef enum {
    MMUMMU_IRQSTATUSTableWalkFaultnTWF_r = 0x0000,
    MMUMMU_IRQSTATUSTableWalkFaultTWFstat_w = 0x0000,
    MMUMMU_IRQSTATUSTableWalkFaultTWF_r = 0x0001,
    MMUMMU_IRQSTATUSTableWalkFaultrTWFstat_w = 0x0001
}   MMUMMU_IRQSTATUSTableWalkFaultE;

typedef enum {
    MMUMMU_IRQSTATUSEMUMissnEMUM_r = 0x0000,
    MMUMMU_IRQSTATUSEMUMissEstat_w = 0x0000,
    MMUMMU_IRQSTATUSEMUMissEMUM_r = 0x0001,
    MMUMMU_IRQSTATUSEMUMissrEstat_w = 0x0001
}   MMUMMU_IRQSTATUSEMUMissE;

typedef enum {
    MMUMMU_IRQSTATUSTranslationFaultnFault_r = 0x0000,
    MMUMMU_IRQSTATUSTranslationFaultFstat_w = 0x0000,
    MMUMMU_IRQSTATUSTranslationFaultFault_r = 0x0001,
    MMUMMU_IRQSTATUSTranslationFaultrFstat_w = 0x0001
}   MMUMMU_IRQSTATUSTranslationFaultE;

typedef enum {
    MMUMMU_IRQSTATUSTLBMissnTLBM_r = 0x0000,
    MMUMMU_IRQSTATUSTLBMissMstat_w = 0x0000,
    MMUMMU_IRQSTATUSTLBMissTLBM_r = 0x0001,
    MMUMMU_IRQSTATUSTLBMissrMstat_w = 0x0001
}   MMUMMU_IRQSTATUSTLBMissE;

typedef enum {
    MMUMMU_IRQENABLEMultiHitFaultMHFltMAsk = 0x0000,
    MMUMMU_IRQENABLEMultiHitFaultMHFltGInt = 0x0001
}   MMUMMU_IRQENABLEMultiHitFaultE;

typedef enum {
    MMUMMU_IRQENABLETableWalkFaultTWLFltMAsk = 0x0000,
    MMUMMU_IRQENABLETableWalkFaultTWLFltGInt = 0x0001
}   MMUMMU_IRQENABLETableWalkFaultE;

typedef enum {
    MMUMMU_IRQENABLEEMUMissEMUMFltMask = 0x0000,
    MMUMMU_IRQENABLEEMUMissEMUMFltGInt = 0x0001
}   MMUMMU_IRQENABLEEMUMissE;

typedef enum {
    MMUMMU_IRQENABLETranslationFaultTranFltMask = 0x0000,
    MMUMMU_IRQENABLETranslationFaultTranFltGInt = 0x0001
}   MMUMMU_IRQENABLETranslationFaultE;

typedef enum {
    MMUMMU_IRQENABLETLBMissTrMissIntM = 0x0000,
    MMUMMU_IRQENABLETLBMissTrMissGInt = 0x0001
}   MMUMMU_IRQENABLETLBMissE;

typedef enum {
    MMUMMU_WALKING_STTWLRunningTWLComp = 0x0000,
    MMUMMU_WALKING_STTWLRunningTWLRun = 0x0001
}   MMUMMU_WALKING_STTWLRunningE;

typedef enum {
    MMUMMU_CNTLEmuTLBUpdateEMUdis = 0x0000,
    MMUMMU_CNTLEmuTLBUpdateEMUen = 0x0001
}   MMUMMU_CNTLEmuTLBUpdateE;

typedef enum {
    MMUMMU_CNTLTWLEnableTWLdis = 0x0000,
    MMUMMU_CNTLTWLEnableTWLen = 0x0001
}   MMUMMU_CNTLTWLEnableE;

typedef enum {
    MMUMMU_CNTLMMUEnableMMUdis = 0x0000,
    MMUMMU_CNTLMMUEnableMMUen = 0x0001
}   MMUMMU_CNTLMMUEnableE;

typedef enum {
    MMUMMU_LD_TLBLdTLBItemalways_r = 0x0000,
    MMUMMU_LD_TLBLdTLBItemnoeffect_w = 0x0000,
    MMUMMU_LD_TLBLdTLBItemnever_r = 0x0001,
    MMUMMU_LD_TLBLdTLBItemldTLB_w = 0x0001
}   MMUMMU_LD_TLBLdTLBItemE;

typedef enum {
    MMUMMU_CAMPCanFlush = 0x0000,
    MMUMMU_CAMPNoFlush = 0x0001
}   MMUMMU_CAMPE;

typedef enum {
    MMUMMU_CAMVInvalid = 0x0000,
    MMUMMU_CAMVValid = 0x0001
}   MMUMMU_CAMVE;

typedef enum {
    MMUMMU_CAMPageSizeSection = 0x0000,
    MMUMMU_CAMPageSizeLarge = 0x0001,
    MMUMMU_CAMPageSizeSmall = 0x0002,
    MMUMMU_CAMPageSizeSuper = 0x0003
}   MMUMMU_CAMPageSizeE;

typedef enum {
    MMUMMU_RAMEndiannessLittle = 0x0000,
    MMUMMU_RAMEndiannessBig = 0x0001
}   MMUMMU_RAMEndiannessE;

typedef enum {
    MMUMMU_RAMElementSizeByte = 0x0000,
    MMUMMU_RAMElementSizeShort = 0x0001,
    MMUMMU_RAMElementSizeLong = 0x0002,
    MMUMMU_RAMElementSizeNone = 0x0003
}   MMUMMU_RAMElementSizeE;

typedef enum {
    MMUMMU_RAMMixedTLBes = 0x0000,
    MMUMMU_RAMMixedCPUes = 0x0001
}   MMUMMU_RAMMixedE;

typedef enum {
    MMUMMU_GFLUSHGlobalFlushrtn0_r = 0x0000,
    MMUMMU_GFLUSHGlobalFlushnft_w = 0x0000,
    MMUMMU_GFLUSHGlobalFlushnever_r = 0x0001,
    MMUMMU_GFLUSHGlobalFlushflush_w = 0x0001
}   MMUMMU_GFLUSHGlobalFlushE;

typedef enum {
    MMUMMU_FLUSH_ENTRYFlushEntryalways_r = 0x0000,
    MMUMMU_FLUSH_ENTRYFlushEntrynofun_w = 0x0000,
    MMUMMU_FLUSH_ENTRYFlushEntrynever_r = 0x0001,
    MMUMMU_FLUSH_ENTRYFlushEntryflushTLB_w = 0x0001
}   MMUMMU_FLUSH_ENTRYFlushEntryE;

typedef enum {
    MMUMMU_READ_CAMPCanFlush = 0x0000,
    MMUMMU_READ_CAMPNoFlush = 0x0001
}   MMUMMU_READ_CAMPE;

typedef enum {
    MMUMMU_READ_CAMVInvalid = 0x0000,
    MMUMMU_READ_CAMVValid = 0x0001
}   MMUMMU_READ_CAMVE;

typedef enum {
    MMUMMU_READ_CAMPageSizeSection = 0x0000,
    MMUMMU_READ_CAMPageSizeLarge = 0x0001,
    MMUMMU_READ_CAMPageSizeSmall = 0x0002,
    MMUMMU_READ_CAMPageSizeSuper = 0x0003
}   MMUMMU_READ_CAMPageSizeE;

typedef enum {
    MMUMMU_READ_RAMEndiannessLittle = 0x0000,
    MMUMMU_READ_RAMEndiannessBig = 0x0001
}   MMUMMU_READ_RAMEndiannessE;

typedef enum {
    MMUMMU_READ_RAMElementSizeByte = 0x0000,
    MMUMMU_READ_RAMElementSizeShort = 0x0001,
    MMUMMU_READ_RAMElementSizeLong = 0x0002,
    MMUMMU_READ_RAMElementSizeNone = 0x0003
}   MMUMMU_READ_RAMElementSizeE;

typedef enum {
    MMUMMU_READ_RAMMixedTLBes = 0x0000,
    MMUMMU_READ_RAMMixedCPUes = 0x0001
}   MMUMMU_READ_RAMMixedE;

/**************************************************************************
* EXPORTED VARIABLES
************************************************************************ */

/**************************************************************************
* EXPORTED FUNCTIONS
*********************************************************************** */

#if defined(__cplusplus)
}	/* End of C++ extern block */
#endif /* defined(__cplusplus) */

#endif /* _MMU_ACC_INT_H */
/* EOF */

