obj-y := librmgr.o

librmgr-objs := common/dbdcd.o common/disp.o common/drv.o common/mgr.o common/node.o \
		common/proc.o common/pwr.o common/rmm.o common/strm.o common/dspdrv.o \
		nldr/nldr.o common/drv_interface.o

ccflags-y = -Wno-strict-prototypes -fomit-frame-pointer -DDISABLE_BRIDGE_DVFS

#Machine dependent
ccflags-y += -D_TI_ -D_DB_TIOMAP -DOMAP_3430
ccflags-y += -DLINUX -D__KERNEL__

#Power management
ifeq ($(CONFIG_PM),)
ccflags-y += -DDISABLE_BRIDGE_PM
endif

#includes
ccflags-y += -I. -Iinclude -Idrivers/dsp/dspbridge/mpu_driver/inc -Idrivers/dsp/dspbridge/mpu_driver/inc/linux -Icommon -Idrivers/dsp/dspbridge/mpu_driver/src/hal/omap3/inc -Idrivers/dsp/dspbridge/mpu_driver/src/hal/omap3/mbox -Idrivers/dsp/dspbridge/mpu_driver/src/hal/omap3/mmu -Idrivers/dsp/dspbridge/mpu_driver/src/hal/omap3/ocp -include include/linux/autoconf.h -Idrivers/dsp/dspbridge/mpu_driver/src/rmgr -Idrivers/dsp/dspbridge/mpu_driver/src/rmgr/common

# Debug
ifeq ($(CONFIG_DEBUG_KERNEL),y)
ccflags-y += -DGT_TRACE -DDEBUG
endif

ifeq ($(CONFIG_MPU_BRIDGE),m)
ccflags-y += -DMODULE
endif
