obj-$(CONFIG_MPU_BRIDGE)	+= bridgedriver.o

libgen = gen/gb.o gen/gt.o gen/gs.o gen/gh.o gen/_gt_para.o gen/uuidutil.o
libservices = services/csl.o services/mem.o services/list.o services/dpc.o \
		services/isr.o services/kfile.o services/sync.o \
		services/clk.o services/cfg.o services/reg.o \
		services/regsup.o services/prcs.o services/ntfy.o \
		services/dbg.o services/services.o
libwmd = wmd/wmdchnl/chnl_sm.o wmd/wmdchnl/msg_sm.o wmd/wmdchnl/io_sm.o \
		wmd/3430/tiomap.o wmd/3430/tiomap_pwr.o wmd/tiomap_mmu.o \
		wmd/tiomap_sm.o wmd/tiomap_io.o wmd/tiomap_util.o \
		wmd/mmu_fault.o wmd/ue_deh.o
libpmgr = pmgr/chnl.o pmgr/io.o pmgr/msg.o pmgr/cod.o pmgr/dev.o pmgr/wcd.o \
		pmgr/dmm.o pmgr/cmm.o pmgr/dbll.o
librmgr = rmgr/dbdcd.o rmgr/disp.o rmgr/drv.o rmgr/mgr.o rmgr/node.o \
		rmgr/proc.o rmgr/pwr.o rmgr/rmm.o rmgr/strm.o rmgr/dspdrv.o \
		rmgr/nldr.o rmgr/drv_interface.o
libdload = dynload/cload.o dynload/getsection.o dynload/reloc.o
libhw = hw/hw_prcm.o hw/hw_dspssC64P.o hw/hw_mmu.o hw/hw_mbox.o

bridgedriver-objs = $(libgen) $(libservices) $(libwmd) $(libpmgr) $(librmgr) \
			$(libdload) $(libhw)

# Disable DVFS
ifeq ($(CONFIG_BRIDGE_DVFS),y)
ccflags-y += -DDISABLE_BRIDGE_DVFS
endif

#Power management
ifeq ($(CONFIG_BRIDGE_PM),y)
ccflags-y = -DDISABLE_BRIDGE_PM
endif

# Debug
ifeq ($(CONFIG_DEBUG_KERNEL),y)
ccflags-y += -DGT_TRACE -DDEBUG
endif

ccflags-y += -Wno-strict-prototypes -fomit-frame-pointer
ccflags-y += -DOPT_ELIMINATE_EXTRA_DLOAD -DOPT_REDUCE_SYMBOL_LOOKUPS \
		-DOPT_USE_MEMSET

#Machine dependent
ccflags-y += -D_TI_ -D_DB_TIOMAP -DOMAP_3430 -D__KERNEL__ -DTMS32060 \
		-DTICFG_PROC_VER -DTICFG_EVM_TYPE -DCHNL_SMCLASS \
		-DCHNL_MESSAGES -DUSE_LEVEL_1_MACROS -D__MPU__

#Header files
ccflags-y += -Idrivers/dsp/bridge/services
ccflags-y += -Idrivers/dsp/bridge/wmd/wmdchnl/ \
		-Idrivers/dsp/bridge/wmd/
ccflags-y += -Idrivers/dsp/bridge/pmgr/
ccflags-y += -Idrivers/dsp/bridge/rmgr/
ccflags-y += -Iinclude -Iarch/arm/plat-omap/include/dspbridge
ccflags-y += -Idrivers/dsp/bridge/hw
